<h2> M. Riziq Sirfatullah Alfarizi </h2>
<h3> I.2211266 </h3>

# Soal Tugas

Lakukan web scraping pada link di bawah ini yaitu Real GDP Growth Rate dengan mengambil 150 baris pertama dari tahun 2020 sampai 2022 dengan target diambil tahun 2023, hitung MSE menggunakan seluruh metode regresi yang pernah dipelajar

# Web Scraping

Web Scraping Adalah proses otomatis untuk mengunduh/mengambil informasi dari halaman website. teknik ini menggunakan program untuk membaca konten website kemudian mengambil data yang diinginkan, seperti gambar, teks, tabel DLL dari format HTML

In [ ]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

url = 'https://en.wikipedia.org/wiki/List_of_countries_by_real_GDP_growth_rate'
page = requests.get(url)

soup = BeautifulSoup(page.text,'html')

In [ ]:
table = soup.find_all('table', class_ = 'wikitable sortable static-row-numbers static-row-header-text')[2] # mengambil table ke 3

In [ ]:
table.find_all('th')

[<th>Country
 </th>,
 <th>2013
 </th>,
 <th>2014
 </th>,
 <th>2015
 </th>,
 <th>2016
 </th>,
 <th>2017
 </th>,
 <th>2018
 </th>,
 <th>2019
 </th>,
 <th>2020
 </th>,
 <th>2021
 </th>,
 <th>2022
 </th>,
 <th>2023
 </th>,
 <th>Avg.
 </th>]

In [ ]:
judul_kolom = table.find_all('th')

list_judul_kolom = [judul.text for judul in judul_kolom]
print(list_judul_kolom)

['Country\n', '2013\n', '2014\n', '2015\n', '2016\n', '2017\n', '2018\n', '2019\n', '2020\n', '2021\n', '2022\n', '2023\n', 'Avg.\n']

In [ ]:
list_judul_kolom = [judul.text.strip() for judul in judul_kolom]
print(list_judul_kolom)

['Country', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', 'Avg.']

In [ ]:
df = pd.DataFrame(columns = list_judul_kolom)
df

Empty DataFrame
Columns: [Country, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, Avg.]
Index: []

In [ ]:
table.find_all('tr')

[<tr>
 <th>Country
 </th>
 <th>2013
 </th>
 <th>2014
 </th>
 <th>2015
 </th>
 <th>2016
 </th>
 <th>2017
 </th>
 <th>2018
 </th>
 <th>2019
 </th>
 <th>2020
 </th>
 <th>2021
 </th>
 <th>2022
 </th>
 <th>2023
 </th>
 <th>Avg.
 </th></tr>,
 <tr>
 <td>Afghanistan
 </td>
 <td>5.683
 </td>
 <td>2.697
 </td>
 <td>0.988
 </td>
 <td>2.164
 </td>
 <td>2.647
 </td>
 <td>1.189
 </td>
 <td>3.912
 </td>
 <td>-2.351
 </td>
 <td>-14.542
 </td>
 <td>-6.240
 </td>
 <td>n/a
 </td>
 <td>-0.385
 </td></tr>,
 <tr>
 <td>Albania
 </td>
 <td>1.002
 </td>
 <td>1.774
 </td>
 <td>2.219
 </td>
 <td>3.315
 </td>
 <td>3.802
 </td>
 <td>4.019
 </td>
 <td>2.088
 </td>
 <td>-3.302
 </td>
 <td>8.909
 </td>
 <td>4.884
 </td>
 <td>3.297
 </td>
 <td>2.906
 </td></tr>,
 <tr>
 <td>Algeria
 </td>
 <td>2.597
 </td>
 <td>4.086
 </td>
 <td>3.162
 </td>
 <td>3.884
 </td>
 <td>1.524
 </td>
 <td>1.440
 </td>
 <td>0.933
 </td>
 <td>-5.017
 </td>
 <td>3.805
 </td>
 <td>3.616
 </td>
 <td>4.184
 </td>
 <td>2.201
 </td></tr>,
 <tr>
 <td>Andorra
 </td>
 <td>-3.548
 </td>
 <td>2.504
 </td>
 <td>1.434
 </td>
 <td>3.710
 </td>
 <td>0.346
 </td>
 <td>1.589
 </td>
 <td>2.016
 </td>
 <td>-11.184
 </td>
 <td>8.287
 </td>
 <td>9.565
 </td>
 <td>2.275
 </td>
 <td>1.545
 </td></tr>,
 <tr>
 <td>Angola
 </td>
 <td>4.955
 </td>
 <td>4.823
 </td>
 <td>0.944
 </td>
 <td>-2.580
 </td>
 <td>-0.150
 </td>
 <td>-1.316
 </td>
 <td>-0.702
 </td>
 <td>-5.638
 </td>
 <td>1.199
 </td>
 <td>3.045
 </td>
 <td>0.470
 </td>
 <td>0.459
 </td></tr>,
 <tr>
 <td>Antigua and Barbuda
 </td>
 <td>-0.601
 </td>
 <td>3.797
 </td>
 <td>3.824
 </td>
 <td>5.497
 </td>
 <td>3.144
 </td>
 <td>6.824
 </td>
 <td>4.344
 </td>
 <td>-17.503
 </td>
 <td>6.556
 </td>
 <td>8.459
 </td>
 <td>5.863
 </td>
 <td>2.746
 </td></tr>,
 <tr>
 <td>Argentina
 </td>
 <td>2.405
 </td>
 <td>-2.513
 </td>
 <td>2.731
 </td>
 <td>-2.080
 </td>
 <td>2.818
 </td>
 <td>-2.617
 </td>
 <td>-2.001
 </td>
 <td>-9.900
 </td>
 <td>10.718
 </td>
 <td>4.956
 </td>
 <td>-1.569
 </td>
 <td>0.268
 </td></tr>,
 <tr>
 <td>Armenia
 </td>
 <td>3.412
 </td>
 <td>3.607
 </td>
 <td>3.254
 </td>
 <td>0.195
 </td>
 <td>7.518
 </td>
 <td>5.225
 </td>
 <td>7.631
 </td>
 <td>-7.151
 </td>
 <td>5.684
 </td>
 <td>12.604
 </td>
 <td>8.714
 </td>
 <td>4.608
 </td></tr>,
 <tr>
 <td>Aruba
 </td>
 <td>6.431
 </td>
 <td>-1.587
 </td>
 <td>-0.264
 </td>
 <td>1.720
 </td>
 <td>7.049
 </td>
 <td>2.382
 </td>
 <td>-2.303
 </td>
 <td>-23.983
 </td>
 <td>27.639
 </td>
 <td>10.458
 </td>
 <td>5.300
 </td>
 <td>2.953
 </td></tr>,
 <tr>
 <td>Australia
 </td>
 <td>2.232
 </td>
 <td>2.586
 </td>
 <td>2.349
 </td>
 <td>2.720
 </td>
 <td>2.420
 </td>
 <td>2.849
 </td>
 <td>1.815
 </td>
 <td>-2.129
 </td>
 <td>5.554
 </td>
 <td>3.811
 </td>
 <td>2.063
 </td>
 <td>2.388
 </td></tr>,
 <tr>
 <td>Austria
 </td>
 <td>0.026
 </td>
 <td>0.661
 </td>
 <td>1.015
 </td>
 <td>1.989
 </td>
 <td>2.259
 </td>
 <td>2.425
 </td>
 <td>1.451
 </td>
 <td>-6.633
 </td>
 <td>4.238
 </td>
 <td>4.806
 </td>
 <td>-0.746
 </td>
 <td>1.045
 </td></tr>,
 <tr>
 <td>Azerbaijan
 </td>
 <td>5.843
 </td>
 <td>2.768
 </td>
 <td>1.080
 </td>
 <td>-3.064
 </td>
 <td>0.154
 </td>
 <td>1.470
 </td>
 <td>2.480
 </td>
 <td>-4.199
 </td>
 <td>5.616
 </td>
 <td>4.577
 </td>
 <td>1.100
 </td>
 <td>1.620
 </td></tr>,
 <tr>
 <td>The Bahamas
 </td>
 <td>-2.863
 </td>
 <td>1.847
 </td>
 <td>0.997
 </td>
 <td>-0.763
 </td>
 <td>2.524
 </td>
 <td>2.918
 </td>
 <td>-0.744
 </td>
 <td>-23.508
 </td>
 <td>16.985
 </td>
 <td>14.369
 </td>
 <td>4.304
 </td>
 <td>1.464
 </td></tr>,
 <tr>
 <td>Bahrain
 </td>
 <td>5.416
 </td>
 <td>4.351
 </td>
 <td>2.485
 </td>
 <td>3.558
 </td>
 <td>4.292
 </td>
 <td>2.110
 </td>
 <td>2.167
 </td>
 <td>-4.645
 </td>
 <td>2.591
 </td>
 <td>4.891
 </td>
 <td>2.617
 </td>
 <td>2.712
 </td></tr>,
 <tr>
 <td>Bangladesh
 </td>
 <td>6.014
 </td>
 <td>6.061
 </td>
 <td>6.553
 </td>
 <td>7.114
 </td>
 <td>6.590
 </td>
 <td>7.319
 </td>
 <td>7.882
 </td>
 <td>3.448
 </td>
 <td>6.939
 </td>
 <td>7.100
 </td>
 <td>6.025
 </td>
 <td>6.459
 </td></tr>,
 <tr>
 <td>Barbados
 </td>
 <td>-1.411
 </td>
 <td>-0.126
 </td>
 <td>2.446
 </td>
 <td>2.485
 </td>
 <td>-0.686
 </td>
 <td>-0.675
 </td>
 <td>0.332
 </td>
 <td>-12.713
 </td>
 <td>-1.324
 </td>
 <td>13.800
 </td>
 <td>4.400
 </td>
 <td>0.593
 </td></tr>,
 <tr>
 <td>Belarus
 </td>
 <td>0.962
 </td>
 <td>1.686
 </td>
 <td>-3.830
 </td>
 <td>-2.536
 </td>
 <td>2.541
 </td>
 <td>3.138
 </td>
 <td>1.446
 </td>
 <td>-0.673
 </td>
 <td>2.439
 </td>
 <td>-4.698
 </td>
 <td>3.882
 </td>
 <td>0.396
 </td></tr>,
 <tr>
 <td>Belgium
 </td>
 <td>0.459
 </td>
 <td>1.579
 </td>
 <td>2.041
 </td>
 <td>1.267
 </td>
 <td>1.620
 </td>
 <td>1.793
 </td>
 <td>2.241
 </td>
 <td>-5.261
 </td>
 <td>6.851
 </td>
 <td>3.010
 </td>
 <td>1.461
 </td>
 <td>1.551
 </td></tr>,
 <tr>
 <td>Belize
 </td>
 <td>4.437
 </td>
 <td>4.006
 </td>
 <td>3.226
 </td>
 <td>-0.009
 </td>
 <td>-1.817
 </td>
 <td>1.056
 </td>
 <td>4.236
 </td>
 <td>-13.731
 </td>
 <td>17.864
 </td>
 <td>8.733
 </td>
 <td>4.699
 </td>
 <td>2.973
 </td></tr>,
 <tr>
 <td>Benin
 </td>
 <td>7.191
 </td>
 <td>6.358
 </td>
 <td>1.778
 </td>
 <td>3.340
 </td>
 <td>5.672
 </td>
 <td>6.697
 </td>
 <td>6.866
 </td>
 <td>3.849
 </td>
 <td>7.155
 </td>
 <td>6.253
 </td>
 <td>5.756
 </td>
 <td>5.538
 </td></tr>,
 <tr>
 <td>Bhutan
 </td>
 <td>3.334
 </td>
 <td>3.705
 </td>
 <td>6.155
 </td>
 <td>7.514
 </td>
 <td>5.855
 </td>
 <td>3.505
 </td>
 <td>4.648
 </td>
 <td>-2.455
 </td>
 <td>-3.293
 </td>
 <td>4.826
 </td>
 <td>4.644
 </td>
 <td>3.494
 </td></tr>,
 <tr>
 <td>Bolivia
 </td>
 <td>6.796
 </td>
 <td>5.461
 </td>
 <td>4.857
 </td>
 <td>4.264
 </td>
 <td>4.195
 </td>
 <td>4.224
 </td>
 <td>2.217
 </td>
 <td>-8.738
 </td>
 <td>6.111
 </td>
 <td>3.606
 </td>
 <td>2.500
 </td>
 <td>3.227
 </td></tr>,
 <tr>
 <td>Bosnia and Herzegovina
 </td>
 <td>2.351
 </td>
 <td>1.148
 </td>
 <td>4.314
 </td>
 <td>3.242
 </td>
 <td>3.244
 </td>
 <td>3.829
 </td>
 <td>2.886
 </td>
 <td>-3.015
 </td>
 <td>7.392
 </td>
 <td>4.227
 </td>
 <td>1.800
 </td>
 <td>2.856
 </td></tr>,
 <tr>
 <td>Botswana
 </td>
 <td>11.103
 </td>
 <td>5.697
 </td>
 <td>-4.851
 </td>
 <td>7.202
 </td>
 <td>4.113
 </td>
 <td>4.190
 </td>
 <td>3.033
 </td>
 <td>-8.726
 </td>
 <td>11.867
 </td>
 <td>5.782
 </td>
 <td>3.245
 </td>
 <td>3.878
 </td></tr>,
 <tr>
 <td>Brazil
 </td>
 <td>3.005
 </td>
 <td>0.504
 </td>
 <td>-3.546
 </td>
 <td>-3.276
 </td>
 <td>1.323
 </td>
 <td>1.784
 </td>
 <td>1.221
 </td>
 <td>-3.277
 </td>
 <td>4.763
 </td>
 <td>3.017
 </td>
 <td>2.908
 </td>
 <td>0.766
 </td></tr>,
 <tr>
 <td>Brunei Darussalam
 </td>
 <td>-2.125
 </td>
 <td>-2.508
 </td>
 <td>-0.405
 </td>
 <td>-2.465
 </td>
 <td>1.329
 </td>
 <td>0.052
 </td>
 <td>3.869
 </td>
 <td>1.134
 </td>
 <td>-1.591
 </td>
 <td>-1.628
 </td>
 <td>1.407
 </td>
 <td>-0.266
 </td></tr>,
 <tr>
 <td>Bulgaria
 </td>
 <td>-0.543
 </td>
 <td>0.949
 </td>
 <td>3.398
 </td>
 <td>3.027
 </td>
 <td>2.746
 </td>
 <td>2.695
 </td>
 <td>4.035
 </td>
 <td>-3.966
 </td>
 <td>7.662
 </td>
 <td>3.926
 </td>
 <td>1.846
 </td>
 <td>2.343
 </td></tr>,
 <tr>
 <td>Burkina Faso
 </td>
 <td>5.793
 </td>
 <td>4.327
 </td>
 <td>3.921
 </td>
 <td>5.958
 </td>
 <td>6.203
 </td>
 <td>6.605
 </td>
 <td>5.486
 </td>
 <td>1.922
 </td>
 <td>6.938
 </td>
 <td>1.780
 </td>
 <td>3.561
 </td>
 <td>4.772
 </td></tr>,
 <tr>
 <td>Burundi
 </td>
 <td>4.924
 </td>
 <td>4.241
 </td>
 <td>-3.900
 </td>
 <td>-0.600
 </td>
 <td>0.500
 </td>
 <td>1.610
 </td>
 <td>1.842
 </td>
 <td>0.335
 </td>
 <td>3.119
 </td>
 <td>1.827
 </td>
 <td>2.659
 </td>
 <td>1.505
 </td></tr>,
 <tr>
 <td>Cabo Verde
 </td>
 <td>0.632
 </td>
 <td>0.697
 </td>
 <td>0.936
 </td>
 <td>4.281
 </td>
 <td>4.551
 </td>
 <td>3.707
 </td>
 <td>6.948
 </td>
 <td>-20.805
 </td>
 <td>5.615
 </td>
 <td>17.117
 </td>
 <td>4.792
 </td>
 <td>2.588
 </td></tr>,
 <tr>
 <td>Cambodia
 </td>
 <td>7.857
 </td>
 <td>8.000
 </td>
 <td>7.207
 </td>
 <td>7.906
 </td>
 <td>8.075
 </td>
 <td>8.776
 </td>
 <td>7.937
 </td>
 <td>-3.556
 </td>
 <td>3.090
 </td>
 <td>5.103
 </td>
 <td>4.988
 </td>
 <td>5.945
 </td></tr>,
 <tr>
 <td>Cameroon
 </td>
 <td>4.987
 </td>
 <td>5.779
 </td>
 <td>5.600
 </td>
 <td>4.479
 </td>
 <td>3.541
 </td>
 <td>4.022
 </td>
 <td>3.422
 </td>
 <td>0.539
 </td>
 <td>3.649
 </td>
 <td>3.595
 </td>
 <td>3.969
 </td>
 <td>3.962
 </td></tr>,
 <tr>
 <td>Canada
 </td>
 <td>2.326
 </td>
 <td>2.873
 </td>
 <td>0.650
 </td>
 <td>1.039
 </td>
 <td>3.034
 </td>
 <td>2.743
 </td>
 <td>1.908
 </td>
 <td>-5.038
 </td>
 <td>5.287
 </td>
 <td>3.820
 </td>
 <td>1.066
 </td>
 <td>1.792
 </td></tr>,
 <tr>
 <td>Central African Republic
 </td>
 <td>-36.392
 </td>
 <td>0.080
 </td>
 <td>4.338
 </td>
 <td>4.750
 </td>
 <td>4.528
 </td>
 <td>3.820
 </td>
 <td>2.970
 </td>
 <td>0.959
 </td>
 <td>0.983
 </td>
 <td>0.472
 </td>
 <td>0.727
 </td>
 <td>-1.160
 </td></tr>,
 <tr>
 <td>Chad
 </td>
 <td>5.637
 </td>
 <td>6.122
 </td>
 <td>1.384
 </td>
 <td>-6.330
 </td>
 <td>-2.030
 </td>
 <td>5.874
 </td>
 <td>6.583
 </td>
 <td>-2.053
 </td>
 <td>-0.914
 </td>
 <td>3.075
 </td>
 <td>4.369
 </td>
 <td>1.974
 </td></tr>,
 <tr>
 <td>Chile
 </td>
 <td>3.309
 </td>
 <td>1.793
 </td>
 <td>2.152
 </td>
 <td>1.753
 </td>
 <td>1.358
 </td>
 <td>3.990
 </td>
 <td>0.634
 </td>
 <td>-6.143
 </td>
 <td>11.334
 </td>
 <td>2.059
 </td>
 <td>0.219
 </td>
 <td>2.042
 </td></tr>,
 <tr>
 <td>China
 </td>
 <td>7.771
 </td>
 <td>7.391
 </td>
 <td>7.018
 </td>
 <td>6.851
 </td>
 <td>6.947
 </td>
 <td>6.751
 </td>
 <td>5.951
 </td>
 <td>2.242
 </td>
 <td>8.450
 </td>
 <td>2.989
 </td>
 <td>5.240
 </td>
 <td>6.146
 </td></tr>,
 <tr>
 <td>Colombia
 </td>
 <td>5.134
 </td>
 <td>4.499
 </td>
 <td>2.956
 </td>
 <td>2.088
 </td>
 <td>1.359
 </td>
 <td>2.564
 </td>
 <td>3.187
 </td>
 <td>-7.186
 </td>
 <td>10.801
 </td>
 <td>7.289
 </td>
 <td>0.612
 </td>
 <td>3.028
 </td></tr>,
 <tr>
 <td>Comoros
 </td>
 <td>4.466
 </td>
 <td>2.107
 </td>
 <td>1.147
 </td>
 <td>3.320
 </td>
 <td>3.816
 </td>
 <td>3.642
 </td>
 <td>1.761
 </td>
 <td>-0.196
 </td>
 <td>2.000
 </td>
 <td>2.603
 </td>
 <td>2.996
 </td>
 <td>2.515
 </td></tr>,
 <tr>
 <td>Democratic Republic of the Congo
 </td>
 <td>9.624
 </td>
 <td>7.302
 </td>
 <td>6.360
 </td>
 <td>0.394
 </td>
 <td>3.658
 </td>
 <td>4.825
 </td>
 <td>4.485
 </td>
 <td>1.671
 </td>
 <td>6.037
 </td>
 <td>8.774
 </td>
 <td>6.140
 </td>
 <td>5.388
 </td></tr>,
 <tr>
 <td>Republic of Congo
 </td>
 <td>-0.712
 </td>
 <td>6.717
 </td>
 <td>-3.551
 </td>
 <td>-4.994
 </td>
 <td>-5.595
 </td>
 <td>-2.304
 </td>
 <td>1.124
 </td>
 <td>-6.268
 </td>
 <td>1.057
 </td>
 <td>1.750
 </td>
 <td>4.033
 </td>
 <td>-0.795
 </td></tr>,
 <tr>
 <td>Costa Rica
 </td>
 <td>2.495
 </td>
 <td>3.542
 </td>
 <td>3.652
 </td>
 <td>4.204
 </td>
 <td>4.158
 </td>
 <td>2.616
 </td>
 <td>2.418
 </td>
 <td>-4.273
 </td>
 <td>7.936
 </td>
 <td>4.551
 </td>
 <td>5.112
 </td>
 <td>3.310
 </td></tr>,
 <tr>
 <td>Côte d'Ivoire
 </td>
 <td>9.272
 </td>
 <td>8.794
 </td>
 <td>8.843
 </td>
 <td>7.172
 </td>
 <td>7.412
 </td>
 <td>4.842
 </td>
 <td>6.721
 </td>
 <td>0.701
 </td>
 <td>7.062
 </td>
 <td>6.862
 </td>
 <td>6.200
 </td>
 <td>6.716
 </td></tr>,
 <tr>
 <td>Croatia
 </td>
 <td>-0.399
 </td>
 <td>-0.423
 </td>
 <td>2.523
 </td>
 <td>3.563
 </td>
 <td>3.398
 </td>
 <td>2.822
 </td>
 <td>3.398
 </td>
 <td>-8.591
 </td>
 <td>13.788
 </td>
 <td>6.343
 </td>
 <td>2.831
 </td>
 <td>2.659
 </td></tr>,
 <tr>
 <td>Cyprus
 </td>
 <td>-6.587
 </td>
 <td>-1.775
 </td>
 <td>3.417
 </td>
 <td>6.574
 </td>
 <td>5.734
 </td>
 <td>5.648
 </td>
 <td>5.537
 </td>
 <td>-3.443
 </td>
 <td>9.910
 </td>
 <td>5.059
 </td>
 <td>2.460
 </td>
 <td>2.958
 </td></tr>,
 <tr>
 <td>Czech Republic
 </td>
 <td>-0.046
 </td>
 <td>2.262
 </td>
 <td>5.388
 </td>
 <td>2.537
 </td>
 <td>5.169
 </td>
 <td>3.220
 </td>
 <td>3.030
 </td>
 <td>-5.503
 </td>
 <td>3.553
 </td>
 <td>2.328
 </td>
 <td>-0.405
 </td>
 <td>1.958
 </td></tr>,
 <tr>
 <td>Denmark
 </td>
 <td>0.935
 </td>
 <td>1.616
 </td>
 <td>2.343
 </td>
 <td>3.248
 </td>
 <td>2.819
 </td>
 <td>1.991
 </td>
 <td>1.493
 </td>
 <td>-2.423
 </td>
 <td>6.845
 </td>
 <td>2.731
 </td>
 <td>1.813
 </td>
 <td>2.128
 </td></tr>,
 <tr>
 <td>Djibouti
 </td>
 <td>5.001
 </td>
 <td>7.193
 </td>
 <td>7.309
 </td>
 <td>7.123
 </td>
 <td>5.458
 </td>
 <td>4.774
 </td>
 <td>5.545
 </td>
 <td>1.316
 </td>
 <td>4.522
 </td>
 <td>3.876
 </td>
 <td>6.989
 </td>
 <td>5.373
 </td></tr>,
 <tr>
 <td>Dominica
 </td>
 <td>-1.000
 </td>
 <td>4.754
 </td>
 <td>-2.732
 </td>
 <td>2.764
 </td>
 <td>-6.619
 </td>
 <td>3.548
 </td>
 <td>5.502
 </td>
 <td>-16.605
 </td>
 <td>6.892
 </td>
 <td>5.648
 </td>
 <td>4.726
 </td>
 <td>0.625
 </td></tr>,
 <tr>
 <td>Dominican Republic
 </td>
 <td>4.875
 </td>
 <td>7.050
 </td>
 <td>6.927
 </td>
 <td>6.659
 </td>
 <td>4.667
 </td>
 <td>6.983
 </td>
 <td>5.052
 </td>
 <td>-6.720
 </td>
 <td>12.272
 </td>
 <td>4.858
 </td>
 <td>2.409
 </td>
 <td>5.003
 </td></tr>,
 <tr>
 <td>Ecuador
 </td>
 <td>7.211
 </td>
 <td>4.226
 </td>
 <td>0.120
 </td>
 <td>-0.688
 </td>
 <td>5.970
 </td>
 <td>1.044
 </td>
 <td>0.165
 </td>
 <td>-9.245
 </td>
 <td>9.818
 </td>
 <td>6.186
 </td>
 <td>2.284
 </td>
 <td>2.463
 </td></tr>,
 <tr>
 <td>Egypt
 </td>
 <td>3.302
 </td>
 <td>2.930
 </td>
 <td>4.360
 </td>
 <td>4.340
 </td>
 <td>4.191
 </td>
 <td>5.327
 </td>
 <td>5.548
 </td>
 <td>3.573
 </td>
 <td>3.253
 </td>
 <td>6.653
 </td>
 <td>3.760
 </td>
 <td>4.294
 </td></tr>,
 <tr>
 <td>El Salvador
 </td>
 <td>2.235
 </td>
 <td>1.704
 </td>
 <td>2.400
 </td>
 <td>2.515
 </td>
 <td>2.262
 </td>
 <td>2.445
 </td>
 <td>2.432
 </td>
 <td>-7.901
 </td>
 <td>11.904
 </td>
 <td>2.799
 </td>
 <td>3.498
 </td>
 <td>2.390
 </td></tr>,
 <tr>
 <td>Equatorial Guinea
 </td>
 <td>-4.133
 </td>
 <td>0.415
 </td>
 <td>-9.110
 </td>
 <td>-8.816
 </td>
 <td>-5.668
 </td>
 <td>-6.237
 </td>
 <td>-5.482
 </td>
 <td>-4.788
 </td>
 <td>-0.377
 </td>
 <td>3.246
 </td>
 <td>-5.947
 </td>
 <td>-4.363
 </td></tr>,
 <tr>
 <td>Eritrea
 </td>
 <td>-10.456
 </td>
 <td>30.934
 </td>
 <td>-20.621
 </td>
 <td>7.391
 </td>
 <td>-10.015
 </td>
 <td>13.032
 </td>
 <td>3.836
 </td>
 <td>n/a
 </td>
 <td>n/a
 </td>
 <td>n/a
 </td>
 <td>n/a
 </td>
 <td>2.014
 </td></tr>,
 <tr>
 <td>Estonia
 </td>
 <td>1.458
 </td>
 <td>3.011
 </td>
 <td>1.853
 </td>
 <td>3.155
 </td>
 <td>5.792
 </td>
 <td>3.784
 </td>
 <td>4.034
 </td>
 <td>-0.965
 </td>
 <td>7.249
 </td>
 <td>-0.461
 </td>
 <td>-3.006
 </td>
 <td>2.355
 </td></tr>,
 <tr>
 <td>Eswatini
 </td>
 <td>3.861
 </td>
 <td>0.923
 </td>
 <td>2.227
 </td>
 <td>1.063
 </td>
 <td>2.027
 </td>
 <td>2.380
 </td>
 <td>2.692
 </td>
 <td>-1.560
 </td>
 <td>10.683
 </td>
 <td>0.476
 </td>
 <td>5.133
 </td>
 <td>2.719
 </td></tr>,
 <tr>
 <td>Ethiopia
 </td>
 <td>9.900
 </td>
 <td>10.300
 </td>
 <td>10.400
 </td>
 <td>8.000
 </td>
 <td>10.210
 </td>
 <td>7.703
 </td>
 <td>9.037
 </td>
 <td>6.057
 </td>
 <td>6.265
 </td>
 <td>6.358
 </td>
 <td>7.176
 </td>
 <td>8.310
 </td></tr>,
 <tr>
 <td>Fiji
 </td>
 <td>4.734
 </td>
 <td>5.604
 </td>
 <td>4.501
 </td>
 <td>2.446
 </td>
 <td>5.353
 </td>
 <td>3.812
 </td>
 <td>-0.581
 </td>
 <td>-17.040
 </td>
 <td>-4.881
 </td>
 <td>20.016
 </td>
 <td>8.045
 </td>
 <td>2.910
 </td></tr>,
 <tr>
 <td>Finland
 </td>
 <td>-0.902
 </td>
 <td>-0.365
 </td>
 <td>0.544
 </td>
 <td>2.811
 </td>
 <td>3.192
 </td>
 <td>1.140
 </td>
 <td>1.224
 </td>
 <td>-2.355
 </td>
 <td>2.838
 </td>
 <td>1.335
 </td>
 <td>-0.957
 </td>
 <td>0.773
 </td></tr>,
 <tr>
 <td>France
 </td>
 <td>0.576
 </td>
 <td>0.956
 </td>
 <td>1.113
 </td>
 <td>1.095
 </td>
 <td>2.291
 </td>
 <td>1.865
 </td>
 <td>1.843
 </td>
 <td>-7.540
 </td>
 <td>6.321
 </td>
 <td>2.526
 </td>
 <td>0.869
 </td>
 <td>1.083
 </td></tr>,
 <tr>
 <td>Gabon
 </td>
 <td>5.517
 </td>
 <td>4.435
 </td>
 <td>3.879
 </td>
 <td>2.091
 </td>
 <td>0.473
 </td>
 <td>0.909
 </td>
 <td>3.823
 </td>
 <td>-1.815
 </td>
 <td>1.468
 </td>
 <td>3.037
 </td>
 <td>2.266
 </td>
 <td>2.371
 </td></tr>,
 <tr>
 <td>The Gambia
 </td>
 <td>2.873
 </td>
 <td>-1.407
 </td>
 <td>4.058
 </td>
 <td>1.943
 </td>
 <td>4.823
 </td>
 <td>7.235
 </td>
 <td>6.222
 </td>
 <td>0.591
 </td>
 <td>5.256
 </td>
 <td>4.905
 </td>
 <td>5.555
 </td>
 <td>3.823
 </td></tr>,
 <tr>
 <td>Georgia
 </td>
 <td>5.134
 </td>
 <td>4.091
 </td>
 <td>3.351
 </td>
 <td>3.450
 </td>
 <td>5.161
 </td>
 <td>6.062
 </td>
 <td>5.380
 </td>
 <td>-6.291
 </td>
 <td>10.644
 </td>
 <td>10.960
 </td>
 <td>7.474
 </td>
 <td>5.038
 </td></tr>,
 <tr>
 <td>Germany
 </td>
 <td>0.432
 </td>
 <td>2.217
 </td>
 <td>1.487
 </td>
 <td>2.230
 </td>
 <td>2.680
 </td>
 <td>0.984
 </td>
 <td>1.071
 </td>
 <td>-3.829
 </td>
 <td>3.169
 </td>
 <td>1.804
 </td>
 <td>-0.305
 </td>
 <td>1.085
 </td></tr>,
 <tr>
 <td>Ghana
 </td>
 <td>7.242
 </td>
 <td>2.856
 </td>
 <td>2.121
 </td>
 <td>3.373
 </td>
 <td>8.129
 </td>
 <td>6.200
 </td>
 <td>6.508
 </td>
 <td>0.514
 </td>
 <td>5.076
 </td>
 <td>3.078
 </td>
 <td>2.259
 </td>
 <td>4.305
 </td></tr>,
 <tr>
 <td>Greece
 </td>
 <td>-2.516
 </td>
 <td>0.476
 </td>
 <td>-0.196
 </td>
 <td>-0.487
 </td>
 <td>1.092
 </td>
 <td>1.668
 </td>
 <td>1.880
 </td>
 <td>-9.316
 </td>
 <td>8.380
 </td>
 <td>5.557
 </td>
 <td>2.011
 </td>
 <td>0.777
 </td></tr>,
 <tr>
 <td>Grenada
 </td>
 <td>2.351
 </td>
 <td>7.342
 </td>
 <td>6.445
 </td>
 <td>3.740
 </td>
 <td>4.439
 </td>
 <td>4.361
 </td>
 <td>0.677
 </td>
 <td>-13.757
 </td>
 <td>4.687
 </td>
 <td>7.321
 </td>
 <td>4.791
 </td>
 <td>2.945
 </td></tr>,
 <tr>
 <td>Guatemala
 </td>
 <td>3.695
 </td>
 <td>4.444
 </td>
 <td>4.092
 </td>
 <td>2.678
 </td>
 <td>3.080
 </td>
 <td>3.407
 </td>
 <td>4.018
 </td>
 <td>-1.792
 </td>
 <td>8.002
 </td>
 <td>4.118
 </td>
 <td>3.474
 </td>
 <td>3.565
 </td></tr>,
 <tr>
 <td>Guinea
 </td>
 <td>3.946
 </td>
 <td>3.697
 </td>
 <td>3.826
 </td>
 <td>10.821
 </td>
 <td>10.300
 </td>
 <td>6.358
 </td>
 <td>5.617
 </td>
 <td>4.709
 </td>
 <td>5.583
 </td>
 <td>3.972
 </td>
 <td>5.700
 </td>
 <td>5.866
 </td></tr>,
 <tr>
 <td>Guinea-Bissau
 </td>
 <td>3.256
 </td>
 <td>0.965
 </td>
 <td>6.134
 </td>
 <td>5.307
 </td>
 <td>4.789
 </td>
 <td>3.761
 </td>
 <td>4.500
 </td>
 <td>1.500
 </td>
 <td>6.400
 </td>
 <td>4.200
 </td>
 <td>4.200
 </td>
 <td>4.092
 </td></tr>,
 <tr>
 <td>Guyana
 </td>
 <td>3.653
 </td>
 <td>1.686
 </td>
 <td>0.687
 </td>
 <td>3.807
 </td>
 <td>3.734
 </td>
 <td>4.441
 </td>
 <td>5.353
 </td>
 <td>43.480
 </td>
 <td>20.060
 </td>
 <td>62.288
 </td>
 <td>32.963
 </td>
 <td>16.559
 </td></tr>,
 <tr>
 <td>Haiti
 </td>
 <td>4.325
 </td>
 <td>1.723
 </td>
 <td>2.563
 </td>
 <td>1.812
 </td>
 <td>2.510
 </td>
 <td>1.668
 </td>
 <td>-1.685
 </td>
 <td>-3.343
 </td>
 <td>-1.798
 </td>
 <td>-1.682
 </td>
 <td>-1.864
 </td>
 <td>0.384
 </td></tr>,
 <tr>
 <td>Honduras
 </td>
 <td>2.792
 </td>
 <td>3.058
 </td>
 <td>3.840
 </td>
 <td>3.893
 </td>
 <td>4.843
 </td>
 <td>3.845
 </td>
 <td>2.653
 </td>
 <td>-8.965
 </td>
 <td>12.534
 </td>
 <td>3.998
 </td>
 <td>3.500
 </td>
 <td>3.272
 </td></tr>,
 <tr>
 <td>Hong Kong SAR
 </td>
 <td>3.102
 </td>
 <td>2.762
 </td>
 <td>2.388
 </td>
 <td>2.175
 </td>
 <td>3.796
 </td>
 <td>2.847
 </td>
 <td>-1.672
 </td>
 <td>-6.545
 </td>
 <td>6.454
 </td>
 <td>-3.681
 </td>
 <td>3.215
 </td>
 <td>1.349
 </td></tr>,
 <tr>
 <td>Hungary
 </td>
 <td>1.803
 </td>
 <td>4.232
 </td>
 <td>3.707
 </td>
 <td>2.201
 </td>
 <td>4.272
 </td>
 <td>5.363
 </td>
 <td>4.864
 </td>
 <td>-4.563
 </td>
 <td>7.086
 </td>
 <td>4.555
 </td>
 <td>-0.908
 </td>
 <td>2.976
 </td></tr>,
 <tr>
 <td>Iceland
 </td>
 <td>4.552
 </td>
 <td>1.687
 </td>
 <td>4.437
 </td>
 <td>6.304
 </td>
 <td>4.195
 </td>
 <td>4.889
 </td>
 <td>1.861
 </td>
 <td>-6.940
 </td>
 <td>5.149
 </td>
 <td>8.881
 </td>
 <td>4.064
 </td>
 <td>3.553
 </td></tr>,
 <tr>
 <td>India
 </td>
 <td>6.386
 </td>
 <td>7.410
 </td>
 <td>7.996
 </td>
 <td>8.256
 </td>
 <td>6.795
 </td>
 <td>6.454
 </td>
 <td>3.871
 </td>
 <td>-5.778
 </td>
 <td>9.690
 </td>
 <td>6.987
 </td>
 <td>7.827
 </td>
 <td>5.990
 </td></tr>,
 <tr>
 <td>Indonesia
 </td>
 <td>5.557
 </td>
 <td>5.007
 </td>
 <td>4.876

In [ ]:
data_kolom = table.find_all('tr')

In [ ]:
for baris in data_kolom:
  data_baris = baris.find_all('td')
  data_baris_individu = [data.text.strip() for data in data_baris]
  print(data_baris_individu)

[]
['Afghanistan', '5.683', '2.697', '0.988', '2.164', '2.647', '1.189', '3.912', '-2.351', '-14.542', '-6.240', 'n/a', '-0.385']
['Albania', '1.002', '1.774', '2.219', '3.315', '3.802', '4.019', '2.088', '-3.302', '8.909', '4.884', '3.297', '2.906']
['Algeria', '2.597', '4.086', '3.162', '3.884', '1.524', '1.440', '0.933', '-5.017', '3.805', '3.616', '4.184', '2.201']
['Andorra', '-3.548', '2.504', '1.434', '3.710', '0.346', '1.589', '2.016', '-11.184', '8.287', '9.565', '2.275', '1.545']
['Angola', '4.955', '4.823', '0.944', '-2.580', '-0.150', '-1.316', '-0.702', '-5.638', '1.199', '3.045', '0.470', '0.459']
['Antigua and Barbuda', '-0.601', '3.797', '3.824', '5.497', '3.144', '6.824', '4.344', '-17.503', '6.556', '8.459', '5.863', '2.746']
['Argentina', '2.405', '-2.513', '2.731', '-2.080', '2.818', '-2.617', '-2.001', '-9.900', '10.718', '4.956', '-1.569', '0.268']
['Armenia', '3.412', '3.607', '3.254', '0.195', '7.518', '5.225', '7.631', '-7.151', '5.684', '12.604', '8.714', '4.608']
['Aruba', '6.431', '-1.587', '-0.264', '1.720', '7.049', '2.382', '-2.303', '-23.983', '27.639', '10.458', '5.300', '2.953']
['Australia', '2.232', '2.586', '2.349', '2.720', '2.420', '2.849', '1.815', '-2.129', '5.554', '3.811', '2.063', '2.388']
['Austria', '0.026', '0.661', '1.015', '1.989', '2.259', '2.425', '1.451', '-6.633', '4.238', '4.806', '-0.746', '1.045']
['Azerbaijan', '5.843', '2.768', '1.080', '-3.064', '0.154', '1.470', '2.480', '-4.199', '5.616', '4.577', '1.100', '1.620']
['The Bahamas', '-2.863', '1.847', '0.997', '-0.763', '2.524', '2.918', '-0.744', '-23.508', '16.985', '14.369', '4.304', '1.464']
['Bahrain', '5.416', '4.351', '2.485', '3.558', '4.292', '2.110', '2.167', '-4.645', '2.591', '4.891', '2.617', '2.712']
['Bangladesh', '6.014', '6.061', '6.553', '7.114', '6.590', '7.319', '7.882', '3.448', '6.939', '7.100', '6.025', '6.459']
['Barbados', '-1.411', '-0.126', '2.446', '2.485', '-0.686', '-0.675', '0.332', '-12.713', '-1.324', '13.800', '4.400', '0.593']
['Belarus', '0.962', '1.686', '-3.830', '-2.536', '2.541', '3.138', '1.446', '-0.673', '2.439', '-4.698', '3.882', '0.396']
['Belgium', '0.459', '1.579', '2.041', '1.267', '1.620', '1.793', '2.241', '-5.261', '6.851', '3.010', '1.461', '1.551']
['Belize', '4.437', '4.006', '3.226', '-0.009', '-1.817', '1.056', '4.236', '-13.731', '17.864', '8.733', '4.699', '2.973']
['Benin', '7.191', '6.358', '1.778', '3.340', '5.672', '6.697', '6.866', '3.849', '7.155', '6.253', '5.756', '5.538']
['Bhutan', '3.334', '3.705', '6.155', '7.514', '5.855', '3.505', '4.648', '-2.455', '-3.293', '4.826', '4.644', '3.494']
['Bolivia', '6.796', '5.461', '4.857', '4.264', '4.195', '4.224', '2.217', '-8.738', '6.111', '3.606', '2.500', '3.227']
['Bosnia and Herzegovina', '2.351', '1.148', '4.314', '3.242', '3.244', '3.829', '2.886', '-3.015', '7.392', '4.227', '1.800', '2.856']
['Botswana', '11.103', '5.697', '-4.851', '7.202', '4.113', '4.190', '3.033', '-8.726', '11.867', '5.782', '3.245', '3.878']
['Brazil', '3.005', '0.504', '-3.546', '-3.276', '1.323', '1.784', '1.221', '-3.277', '4.763', '3.017', '2.908', '0.766']
['Brunei Darussalam', '-2.125', '-2.508', '-0.405', '-2.465', '1.329', '0.052', '3.869', '1.134', '-1.591', '-1.628', '1.407', '-0.266']
['Bulgaria', '-0.543', '0.949', '3.398', '3.027', '2.746', '2.695', '4.035', '-3.966', '7.662', '3.926', '1.846', '2.343']
['Burkina Faso', '5.793', '4.327', '3.921', '5.958', '6.203', '6.605', '5.486', '1.922', '6.938', '1.780', '3.561', '4.772']
['Burundi', '4.924', '4.241', '-3.900', '-0.600', '0.500', '1.610', '1.842', '0.335', '3.119', '1.827', '2.659', '1.505']
['Cabo Verde', '0.632', '0.697', '0.936', '4.281', '4.551', '3.707', '6.948', '-20.805', '5.615', '17.117', '4.792', '2.588']
['Cambodia', '7.857', '8.000', '7.207', '7.906', '8.075', '8.776', '7.937', '-3.556', '3.090', '5.103', '4.988', '5.945']
['Cameroon', '4.987', '5.779', '5.600', '4.479', '3.541', '4.022', '3.422', '0.539', '3.649', '3.595', '3.969', '3.962']
['Canada', '2.326', '2.873', '0.650', '1.039', '3.034', '2.743', '1.908', '-5.038', '5.287', '3.820', '1.066', '1.792']
['Central African Republic', '-36.392', '0.080', '4.338', '4.750', '4.528', '3.820', '2.970', '0.959', '0.983', '0.472', '0.727', '-1.160']
['Chad', '5.637', '6.122', '1.384', '-6.330', '-2.030', '5.874', '6.583', '-2.053', '-0.914', '3.075', '4.369', '1.974']
['Chile', '3.309', '1.793', '2.152', '1.753', '1.358', '3.990', '0.634', '-6.143', '11.334', '2.059', '0.219', '2.042']
['China', '7.771', '7.391', '7.018', '6.851', '6.947', '6.751', '5.951', '2.242', '8.450', '2.989', '5.240', '6.146']
['Colombia', '5.134', '4.499', '2.956', '2.088', '1.359', '2.564', '3.187', '-7.186', '10.801', '7.289', '0.612', '3.028']
['Comoros', '4.466', '2.107', '1.147', '3.320', '3.816', '3.642', '1.761', '-0.196', '2.000', '2.603', '2.996', '2.515']
['Democratic Republic of the Congo', '9.624', '7.302', '6.360', '0.394', '3.658', '4.825', '4.485', '1.671', '6.037', '8.774', '6.140', '5.388']
['Republic of Congo', '-0.712', '6.717', '-3.551', '-4.994', '-5.595', '-2.304', '1.124', '-6.268', '1.057', '1.750', '4.033', '-0.795']
['Costa Rica', '2.495', '3.542', '3.652', '4.204', '4.158', '2.616', '2.418', '-4.273', '7.936', '4.551', '5.112', '3.310']
["Côte d'Ivoire", '9.272', '8.794', '8.843', '7.172', '7.412', '4.842', '6.721', '0.701', '7.062', '6.862', '6.200', '6.716']
['Croatia', '-0.399', '-0.423', '2.523', '3.563', '3.398', '2.822', '3.398', '-8.591', '13.788', '6.343', '2.831', '2.659']
['Cyprus', '-6.587', '-1.775', '3.417', '6.574', '5.734', '5.648', '5.537', '-3.443', '9.910', '5.059', '2.460', '2.958']
['Czech Republic', '-0.046', '2.262', '5.388', '2.537', '5.169', '3.220', '3.030', '-5.503', '3.553', '2.328', '-0.405', '1.958']
['Denmark', '0.935', '1.616', '2.343', '3.248', '2.819', '1.991', '1.493', '-2.423', '6.845', '2.731', '1.813', '2.128']
['Djibouti', '5.001', '7.193', '7.309', '7.123', '5.458', '4.774', '5.545', '1.316', '4.522', '3.876', '6.989', '5.373']
['Dominica', '-1.000', '4.754', '-2.732', '2.764', '-6.619', '3.548', '5.502', '-16.605', '6.892', '5.648', '4.726', '0.625']
['Dominican Republic', '4.875', '7.050', '6.927', '6.659', '4.667', '6.983', '5.052', '-6.720', '12.272', '4.858', '2.409', '5.003']
['Ecuador', '7.211', '4.226', '0.120', '-0.688', '5.970', '1.044', '0.165', '-9.245', '9.818', '6.186', '2.284', '2.463']
['Egypt', '3.302', '2.930', '4.360', '4.340', '4.191', '5.327', '5.548', '3.573', '3.253', '6.653', '3.760', '4.294']
['El Salvador', '2.235', '1.704', '2.400', '2.515', '2.262', '2.445', '2.432', '-7.901', '11.904', '2.799', '3.498', '2.390']
['Equatorial Guinea', '-4.133', '0.415', '-9.110', '-8.816', '-5.668', '-6.237', '-5.482', '-4.788', '-0.377', '3.246', '-5.947', '-4.363']
['Eritrea', '-10.456', '30.934', '-20.621', '7.391', '-10.015', '13.032', '3.836', 'n/a', 'n/a', 'n/a', 'n/a', '2.014']
['Estonia', '1.458', '3.011', '1.853', '3.155', '5.792', '3.784', '4.034', '-0.965', '7.249', '-0.461', '-3.006', '2.355']
['Eswatini', '3.861', '0.923', '2.227', '1.063', '2.027', '2.380', '2.692', '-1.560', '10.683', '0.476', '5.133', '2.719']
['Ethiopia', '9.900', '10.300', '10.400', '8.000', '10.210', '7.703', '9.037', '6.057', '6.265', '6.358', '7.176', '8.310']
['Fiji', '4.734', '5.604', '4.501', '2.446', '5.353', '3.812', '-0.581', '-17.040', '-4.881', '20.016', '8.045', '2.910']
['Finland', '-0.902', '-0.365', '0.544', '2.811', '3.192', '1.140', '1.224', '-2.355', '2.838', '1.335', '-0.957', '0.773']
['France', '0.576', '0.956', '1.113', '1.095', '2.291', '1.865', '1.843', '-7.540', '6.321', '2.526', '0.869', '1.083']
['Gabon', '5.517', '4.435', '3.879', '2.091', '0.473', '0.909', '3.823', '-1.815', '1.468', '3.037', '2.266', '2.371']
['The Gambia', '2.873', '-1.407', '4.058', '1.943', '4.823', '7.235', '6.222', '0.591', '5.256', '4.905', '5.555', '3.823']
['Georgia', '5.134', '4.091', '3.351', '3.450', '5.161', '6.062', '5.380', '-6.291', '10.644', '10.960', '7.474', '5.038']
['Germany', '0.432', '2.217', '1.487', '2.230', '2.680', '0.984', '1.071', '-3.829', '3.169', '1.804', '-0.305', '1.085']
['Ghana', '7.242', '2.856', '2.121', '3.373', '8.129', '6.200', '6.508', '0.514', '5.076', '3.078', '2.259', '4.305']
['Greece', '-2.516', '0.476', '-0.196', '-0.487', '1.092', '1.668', '1.880', '-9.316', '8.380', '5.557', '2.011', '0.777']
['Grenada', '2.351', '7.342', '6.445', '3.740', '4.439', '4.361', '0.677', '-13.757', '4.687', '7.321', '4.791', '2.945']
['Guatemala', '3.695', '4.444', '4.092', '2.678', '3.080', '3.407', '4.018', '-1.792', '8.002', '4.118', '3.474', '3.565']
['Guinea', '3.946', '3.697', '3.826', '10.821', '10.300', '6.358', '5.617', '4.709', '5.583', '3.972', '5.700', '5.866']
['Guinea-Bissau', '3.256', '0.965', '6.134', '5.307', '4.789', '3.761', '4.500', '1.500', '6.400', '4.200', '4.200', '4.092']
['Guyana', '3.653', '1.686', '0.687', '3.807', '3.734', '4.441', '5.353', '43.480', '20.060', '62.288', '32.963', '16.559']
['Haiti', '4.325', '1.723', '2.563', '1.812', '2.510', '1.668', '-1.685', '-3.343', '-1.798', '-1.682', '-1.864', '0.384']
['Honduras', '2.792', '3.058', '3.840', '3.893', '4.843', '3.845', '2.653', '-8.965', '12.534', '3.998', '3.500', '3.272']
['Hong Kong SAR', '3.102', '2.762', '2.388', '2.175', '3.796', '2.847', '-1.672', '-6.545', '6.454', '-3.681', '3.215', '1.349']
['Hungary', '1.803', '4.232', '3.707', '2.201', '4.272', '5.363', '4.864', '-4.563', '7.086', '4.555', '-0.908', '2.976']
['Iceland', '4.552', '1.687', '4.437', '6.304', '4.195', '4.889', '1.861', '-6.940', '5.149', '8.881', '4.064', '3.553']
['India', '6.386', '7.410', '7.996', '8.256', '6.795', '6.454', '3.871', '-5.778', '9.690', '6.987', '7.827', '5.990']
['Indonesia', '5.557', '5.007', '4.876', '5.033', '5.070', '5.174', '5.019', '-2.066', '3.703', '5.307', '5.048', '4.339']
['Iran', '-1.522', '4.985', '-1.425', '8.815', '2.759', '-1.838', '-3.071', '3.330', '4.720', '3.777', '4.709', '2.294']
['Iraq', '7.628', '0.738', '2.537', '15.199', '-3.399', '4.703', '5.368', '-12.055', '1.580', '6.983', '-2.176', '2.464']
['Ireland', '1.175', '8.829', '24.475', '1.766', '9.311', '8.471', '5.298', '6.617', '15.125', '9.433', '-3.199', '7.936']
['Israel', '4.231', '3.885', '2.314', '4.367', '4.273', '4.075', '3.785', '-1.465', '9.344', '6.470', '2.003', '3.935']
['Italy', '-1.841', '-0.005', '0.778', '1.293', '1.668', '0.926', '0.483', '-8.974', '8.310', '3.986', '0.921', '0.686']
['Jamaica', '0.224', '0.575', '0.869', '1.498', '0.679', '1.827', '0.970', '-9.920', '4.601', '5.222', '2.200', '0.795']
['Japan', '2.005', '0.296', '1.561', '0.754', '1.675', '0.643', '-0.402', '-4.147', '2.559', '0.957', '1.923', '0.711']
['Jordan', '2.610', '3.384', '2.497', '1.994', '2.474', '1.919', '1.751', '-1.103', '3.656', '2.428', '2.600', '2.201']
['Kazakhstan', '5.899', '4.300', '1.000', '0.900', '3.901', '4.100', '4.500', '-2.600', '4.100', '3.299', '5.101', '3.136']
['Kenya', '3.798', '5.020', '4.968', '4.214', '3.816', '5.671', '5.114', '-0.273', '7.590', '4.847', '5.507', '4.570']
['Kiribati', '7.731', '1.264', '11.265', '7.088', '3.749', '3.479', '3.264', '-0.562', '8.523', '3.905', '4.154', '4.896']
['Korea', '3.165', '3.202', '2.809', '2.947', '3.160', '2.907', '2.244', '-0.709', '4.305', '2.613', '1.357', '2.545']
['Kosovo', '5.340', '3.349', '5.916', '5.572', '4.825', '3.406', '4.757', '-5.341', '10.746', '4.278', '3.300', '4.195']
['Kuwait', '1.149', '0.501', '0.593', '2.926', '-4.712', '2.434', '1.328', '-5.274', '1.698', '6.138', '-2.231', '0.419']
['Kyrgyz Republic', '10.915', '4.024', '3.876', '4.336', '4.740', '3.459', '4.601', '-7.149', '5.507', '6.332', '4.196', '4.076']
['Lao P.D.R.', '8.026', '7.612', '7.270', '7.023', '6.851', '6.289', '4.652', '-0.435', '2.061', '2.252', '3.697', '5.027']
['Latvia', '2.008', '1.902', '3.885', '2.369', '3.312', '3.991', '0.588', '-3.514', '6.732', '2.955', '-0.306', '2.157']
['Lebanon', '3.828', '2.485', '0.461', '1.556', '0.903', '-1.885', '-6.915', '-25.907', '-10.000', 'n/a', 'n/a', '-3.942']
['Lesotho', '1.772', '2.068', '3.248', '1.887', '-2.734', '-1.510', '-3.058', '-5.303', '1.700', '1.600', '1.877', '0.140']
['Liberia', '8.836', '0.695', '0.007', '-1.630', '2.469', '1.242', '-2.516', '-2.967', '5.011', '4.811', '4.583', '1.867']
['Libya', '-17.998', '-23.043', '-0.843', '-1.493', '32.492', '7.941', '-11.196', '-29.456', '28.335', '-8.252', '10.156', '-1.214']
['Lithuania', '3.550', '3.537', '2.025', '2.519', '4.283', '3.993', '4.666', '-0.025', '6.285', '2.440', '-0.343', '2.994']
['Luxembourg', '3.172', '2.623', '2.269', '4.978', '1.317', '1.219', '2.916', '-0.910', '7.169', '1.380', '-1.095', '2.276']
['Macau SAR', '10.753', '-2.048', '-21.515', '-0.679', '9.860', '6.405', '-2.563', '-54.336', '23.535', '-21.402', '80.534', '2.595']
['Madagascar', '2.300', '3.339', '3.132', '3.993', '3.933', '3.194', '4.411', '-7.138', '5.740', '4.000', '3.800', '2.791']
['Malawi', '5.200', '5.700', '2.950', '2.270', '4.000', '4.392', '5.448', '0.913', '4.567', '0.800', '1.600', '3.440']
['Malaysia', '4.694', '6.007', '5.007', '4.450', '5.813', '4.843', '4.413', '-5.457', '3.298', '8.650', '3.680', '4.127']
['Maldives', '6.963', '7.801', '3.972', '6.572', '7.055', '8.668', '7.298', '-32.909', '37.687', '13.907', '4.424', '6.494']
['Mali', '2.295', '7.085', '6.172', '5.852', '5.305', '4.746', '4.765', '-1.244', '3.053', '3.475', '4.500', '4.182']
['Malta', '5.473', '7.634', '9.608', '3.381', '10.869', '7.416', '7.124', '-8.157', '12.514', '8.076', '5.614', '6.323']
['Marshall Islands', '3.610', '-1.158', '2.101', '2.144', '3.734', '5.659', '10.358', '-2.846', '1.112', '-0.676', '3.000', '2.458']
['Mauritania', '4.151', '4.275', '5.376', '1.261', '6.271', '4.773', '3.146', '-0.429', '0.737', '6.364', '4.811', '3.703']
['Mauritius', '3.360', '3.827', '3.691', '3.862', '3.938', '4.007', '2.891', '-14.547', '3.404', '8.881', '6.870', '2.744']
['Mexico', '0.852', '2.504', '2.702', '1.772', '1.872', '1.972', '-0.251', '-8.625', '5.739', '3.949', '3.229', '1.429']
['Micronesia', '-3.676', '-2.586', '4.434', '0.943', '2.255', '0.064', '3.820', '-1.870', '3.013', '-0.864', '0.766', '0.573']
['Moldova', '9.044', '5.000', '-0.338', '4.409', '4.200', '4.100', '3.600', '-8.300', '13.900', '-4.982', '1.032', '2.879']
['Mongolia', '11.649', '7.885', '2.410', '1.490', '5.637', '7.745', '5.602', '-4.558', '1.637', '5.033', '7.023', '4.687']
['Montenegro', '3.549', '1.784', '3.390', '2.949', '4.716', '5.078', '4.063', '-15.307', '13.043', '6.407', '6.000', '3.243']
['Morocco', '4.535', '2.669', '4.345', '0.521', '5.058', '3.066', '2.891', '-7.178', '8.021', '1.259', '3.017', '2.564']
['Mozambique', '6.571', '7.703', '7.393', '4.697', '2.638', '3.485', '2.318', '-1.220', '2.377', '4.360', '6.013', '4.212']
['Myanmar', '7.899', '8.200', '7.473', '6.408', '5.750', '6.405', '6.750', '-1.200', '-10.486', '-3.965', '2.546', '3.253']
['Namibia', '5.615', '6.093', '4.264', '0.034', '-1.027', '1.060', '-0.839', '-8.101', '3.525', '4.560', '3.154', '1.667']
['Nauru', '3.648', '16.423', '2.698', '4.363', '-6.011', '-1.219', '8.407', '1.982', '7.207', '2.841', '0.596', '3.729']
['Nepal', '3.525', '6.011', '3.976', '0.433', '8.977', '7.622', '6.657', '-2.370', '4.838', '5.613', '0.832', '4.192']
['Netherlands', '-0.127', '1.424', '1.958', '2.192', '2.911', '2.361', '1.955', '-3.885', '6.192', '4.326', '0.093', '1.764']
['New Zealand', '2.319', '3.766', '3.636', '3.945', '3.346', '3.497', '3.079', '-1.370', '5.628', '2.384', '0.633', '2.806']
['Nicaragua', '4.927', '4.785', '4.792', '4.563', '4.631', '-3.363', '-2.897', '-1.766', '10.347', '3.751', '4.686', '3.132']
['Niger', '5.311', '6.644', '4.393', '5.741', '5.001', '7.007', '6.143', '3.550', '1.399', '11.904', '1.409', '5.318']
['Nigeria', '5.394', '6.310', '2.653', '-1.617', '0.806', '1.923', '2.208', '-1.794', '3.647', '3.252', '2.860', '2.331']
['North Macedonia', '2.925', '3.629', '3.856', '2.848', '1.082', '2.881', '3.910', '-4.688', '4.511', '2.221', '1.027', '2.200']
['Norway', '1.016', '2.048', '1.857', '1.165', '2.464', '0.829', '1.124', '-1.278', '3.909', '3.006', '0.514', '1.514']
['Oman', '5.227', '1.292', '5.017', '5.046', '0.304', '1.287', '-1.130', '-3.378', '3.092', '4.311', '1.311', '2.034']
['Pakistan', '3.856', '3.556', '3.812', '4.072', '4.609', '6.096', '3.120', '-0.943', '5.770', '6.169', '-0.166', '3.632']
['Palau', '-1.612', '4.435', '9.549', '1.507', '-3.514', '1.261', '1.357', '-7.040', '-13.362', '-1.964', '0.800', '-0.780']
['Panama', '6.903', '5.067', '5.733', '4.953', '5.591', '3.685', '3.282', '-17.668', '15.836', '10.809', '7.317', '4.683']
['Papua New Guinea', '3.825', '13.544', '6.576', '5.492', '3.535', '-0.279', '4.480', '-3.167', '-0.780', '5.165', '2.681', '3.734']
['Paraguay', '8.293', '5.301', '2.957', '4.268', '4.810', '3.204', '-0.402', '-0.820', '4.017', '0.176', '4.477', '3.298']
['Peru', '5.852', '2.384', '3.252', '3.954', '2.522', '3.970', '2.240', '-10.869', '13.418', '2.684', '-0.552', '2.623']
['Philippines', '6.751', '6.348', '6.348', '7.149', '6.931', '6.341', '6.119', '-9.518', '5.715', '7.570', '5.568', '5.029']
['Poland', '0.857', '3.837', '4.383', '2.954', '5.140', '5.945', '4.450', '-2.020', '6.935', '5.260', '0.160', '3.446']
['Portugal', '-0.923', '0.792', '1.792', '2.019', '3.506', '2.849', '2.683', '-8.301', '5.737', '6.828', '2.280', '1.751']
['Puerto Rico', '-0.307', '-1.190', '-1.049', '-1.263', '-2.886', '-4.364', '1.679', '-4.186', '0.412', '3.207', '-0.700', '-0.968']
['Qatar', '5.556', '5.334', '4.753', '3.064', '-1.498', '1.235', '0.688', '-3.558', '1.627', '4.200', '1.558', '2.087']
['Romania', '0.270', '4.121', '3.160', '2.858', '8.197', '6.029', '3.853', '-3.677', '5.709', '4.595', '2.110', '3.384']
['Russia', '1.755', '0.736', '-1.973', '0.194', '1.827', '2.806', '2.198', '-2.654', '5.988', '-1.201', '3.585', '1.206']
['Rwanda', '4.730', '6.154', '8.867', '5.969', '3.931', '8.539', '9.472', '-3.380', '10.880', '8.158', '6.949', '6.388']
['Samoa', '0.107', '0.660', '3.850', '7.984', '1.406', '-0.610', '4.453', '-3.108', '-7.077', '-5.308', '7.990', '0.941']
['San Marino', '-0.820', '-0.649', '2.691', '2.338', '0.254', '1.484', '2.032', '-6.812', '14.228', '5.037', '2.304', '2.008']
['São Tomé and Príncipe', '5.120', '4.906', '1.540', '5.177', '4.113', '4.378', '2.014', '2.625', '1.899', '0.065', '-0.300', '2.867']
['Saudi Arabia', '2.535', '3.811', '4.509', '1.885', '0.911', '3.199', '1.098', '-3.582', '5.075', '7.486', '-0.755', '2.379']
['Senegal', '2.412', '6.224', '6.367', '6.356', '7.407', '6.209', '4.614', '1.342', '6.540', '4.000', '4.102', '5.052']
['Serbia', '2.893', '-1.590', '1.806', '3.339', '2.101', '4.495', '4.332', '-0.903', '7.726', '2.550', '2.528', '2.662']
['Seychelles', '6.403', '4.717', '8.913', '12.118', '6.957', '4.937', '5.513', '-11.741', '0.554', '14.978', '3.679', '5.184']
['Sierra Leone', '20.720', '4.555', '-20.493', '6.354', '3.765', '3.465', '5.254', '-1.969', '4.105', '3.458', '3.392', '2.964']
['Singapore', '4.818', '3.936', '2.977', '3.589', '4.513', '3.517', '1.345', '-3.870', '9.691', '3.838', '1.075', '3.221']
['Slovak Republic', '0.633', '2.697', '5.176', '1.944', '2.938', '4.030', '2.511', '-3.335', '4.789', '1.750', '1.150', '2.207']
['Slovenia', '-1.029', '2.768', '2.210', '3.192', '4.816', '4.455', '3.523', '-4.241', '8.229', '2.461', '1.587', '2.543']
['Solomon Islands', '5.237', '1.186', '1.678', '5.556', '3.077', '2.745', '1.749', '-3.383', '2.564', '2.403', '2.950', '2.342']
['Somalia', '5.655', '2.774', '4.589', '-1.275', '9.500', '2.994', '3.627', '-2.560', '3.308', '2.433', '2.800', '3.074']
['South Africa', '2.485', '1.414', '1.322', '0.665', '1.158', '1.557', '0.260', '-5.963', '4.703', '1.910', '0.602', '0.919']
['South Sudan', '27.272', '1.556', '-0.231', '-13.299', '-5.794', '-2.149', '0.856', '-6.494', '5.329', '-5.186', '-0.070', '0.163']
['Spain', '-1.401', '1.398', '3.837', '3.038', '2.977', '2.283', '1.983', '-11.165', '6.400', '5.771', '2.501', '1.602']

# Mengambil 150 baris pertama dan Pindahkan data ke DataFrame

In [ ]:
for baris in data_kolom[1:151]: # baris di mulai dari 1 dan seterusnya
  data_baris = baris.find_all('td')
  data_baris_individu = [data.text.strip() for data in data_baris]
  print(data_baris_individu)
  # pindah data ke dataframe
  panjang = len(df)
  df.loc[panjang] = data_baris_individu

['Afghanistan', '5.683', '2.697', '0.988', '2.164', '2.647', '1.189', '3.912', '-2.351', '-14.542', '-6.240', 'n/a', '-0.385']
['Albania', '1.002', '1.774', '2.219', '3.315', '3.802', '4.019', '2.088', '-3.302', '8.909', '4.884', '3.297', '2.906']
['Algeria', '2.597', '4.086', '3.162', '3.884', '1.524', '1.440', '0.933', '-5.017', '3.805', '3.616', '4.184', '2.201']
['Andorra', '-3.548', '2.504', '1.434', '3.710', '0.346', '1.589', '2.016', '-11.184', '8.287', '9.565', '2.275', '1.545']
['Angola', '4.955', '4.823', '0.944', '-2.580', '-0.150', '-1.316', '-0.702', '-5.638', '1.199', '3.045', '0.470', '0.459']
['Antigua and Barbuda', '-0.601', '3.797', '3.824', '5.497', '3.144', '6.824', '4.344', '-17.503', '6.556', '8.459', '5.863', '2.746']
['Argentina', '2.405', '-2.513', '2.731', '-2.080', '2.818', '-2.617', '-2.001', '-9.900', '10.718', '4.956', '-1.569', '0.268']
['Armenia', '3.412', '3.607', '3.254', '0.195', '7.518', '5.225', '7.631', '-7.151', '5.684', '12.604', '8.714', '4.608']
['Aruba', '6.431', '-1.587', '-0.264', '1.720', '7.049', '2.382', '-2.303', '-23.983', '27.639', '10.458', '5.300', '2.953']
['Australia', '2.232', '2.586', '2.349', '2.720', '2.420', '2.849', '1.815', '-2.129', '5.554', '3.811', '2.063', '2.388']
['Austria', '0.026', '0.661', '1.015', '1.989', '2.259', '2.425', '1.451', '-6.633', '4.238', '4.806', '-0.746', '1.045']
['Azerbaijan', '5.843', '2.768', '1.080', '-3.064', '0.154', '1.470', '2.480', '-4.199', '5.616', '4.577', '1.100', '1.620']
['The Bahamas', '-2.863', '1.847', '0.997', '-0.763', '2.524', '2.918', '-0.744', '-23.508', '16.985', '14.369', '4.304', '1.464']
['Bahrain', '5.416', '4.351', '2.485', '3.558', '4.292', '2.110', '2.167', '-4.645', '2.591', '4.891', '2.617', '2.712']
['Bangladesh', '6.014', '6.061', '6.553', '7.114', '6.590', '7.319', '7.882', '3.448', '6.939', '7.100', '6.025', '6.459']
['Barbados', '-1.411', '-0.126', '2.446', '2.485', '-0.686', '-0.675', '0.332', '-12.713', '-1.324', '13.800', '4.400', '0.593']
['Belarus', '0.962', '1.686', '-3.830', '-2.536', '2.541', '3.138', '1.446', '-0.673', '2.439', '-4.698', '3.882', '0.396']
['Belgium', '0.459', '1.579', '2.041', '1.267', '1.620', '1.793', '2.241', '-5.261', '6.851', '3.010', '1.461', '1.551']
['Belize', '4.437', '4.006', '3.226', '-0.009', '-1.817', '1.056', '4.236', '-13.731', '17.864', '8.733', '4.699', '2.973']
['Benin', '7.191', '6.358', '1.778', '3.340', '5.672', '6.697', '6.866', '3.849', '7.155', '6.253', '5.756', '5.538']
['Bhutan', '3.334', '3.705', '6.155', '7.514', '5.855', '3.505', '4.648', '-2.455', '-3.293', '4.826', '4.644', '3.494']
['Bolivia', '6.796', '5.461', '4.857', '4.264', '4.195', '4.224', '2.217', '-8.738', '6.111', '3.606', '2.500', '3.227']
['Bosnia and Herzegovina', '2.351', '1.148', '4.314', '3.242', '3.244', '3.829', '2.886', '-3.015', '7.392', '4.227', '1.800', '2.856']
['Botswana', '11.103', '5.697', '-4.851', '7.202', '4.113', '4.190', '3.033', '-8.726', '11.867', '5.782', '3.245', '3.878']
['Brazil', '3.005', '0.504', '-3.546', '-3.276', '1.323', '1.784', '1.221', '-3.277', '4.763', '3.017', '2.908', '0.766']
['Brunei Darussalam', '-2.125', '-2.508', '-0.405', '-2.465', '1.329', '0.052', '3.869', '1.134', '-1.591', '-1.628', '1.407', '-0.266']
['Bulgaria', '-0.543', '0.949', '3.398', '3.027', '2.746', '2.695', '4.035', '-3.966', '7.662', '3.926', '1.846', '2.343']
['Burkina Faso', '5.793', '4.327', '3.921', '5.958', '6.203', '6.605', '5.486', '1.922', '6.938', '1.780', '3.561', '4.772']
['Burundi', '4.924', '4.241', '-3.900', '-0.600', '0.500', '1.610', '1.842', '0.335', '3.119', '1.827', '2.659', '1.505']
['Cabo Verde', '0.632', '0.697', '0.936', '4.281', '4.551', '3.707', '6.948', '-20.805', '5.615', '17.117', '4.792', '2.588']
['Cambodia', '7.857', '8.000', '7.207', '7.906', '8.075', '8.776', '7.937', '-3.556', '3.090', '5.103', '4.988', '5.945']
['Cameroon', '4.987', '5.779', '5.600', '4.479', '3.541', '4.022', '3.422', '0.539', '3.649', '3.595', '3.969', '3.962']
['Canada', '2.326', '2.873', '0.650', '1.039', '3.034', '2.743', '1.908', '-5.038', '5.287', '3.820', '1.066', '1.792']
['Central African Republic', '-36.392', '0.080', '4.338', '4.750', '4.528', '3.820', '2.970', '0.959', '0.983', '0.472', '0.727', '-1.160']
['Chad', '5.637', '6.122', '1.384', '-6.330', '-2.030', '5.874', '6.583', '-2.053', '-0.914', '3.075', '4.369', '1.974']
['Chile', '3.309', '1.793', '2.152', '1.753', '1.358', '3.990', '0.634', '-6.143', '11.334', '2.059', '0.219', '2.042']
['China', '7.771', '7.391', '7.018', '6.851', '6.947', '6.751', '5.951', '2.242', '8.450', '2.989', '5.240', '6.146']
['Colombia', '5.134', '4.499', '2.956', '2.088', '1.359', '2.564', '3.187', '-7.186', '10.801', '7.289', '0.612', '3.028']
['Comoros', '4.466', '2.107', '1.147', '3.320', '3.816', '3.642', '1.761', '-0.196', '2.000', '2.603', '2.996', '2.515']
['Democratic Republic of the Congo', '9.624', '7.302', '6.360', '0.394', '3.658', '4.825', '4.485', '1.671', '6.037', '8.774', '6.140', '5.388']
['Republic of Congo', '-0.712', '6.717', '-3.551', '-4.994', '-5.595', '-2.304', '1.124', '-6.268', '1.057', '1.750', '4.033', '-0.795']
['Costa Rica', '2.495', '3.542', '3.652', '4.204', '4.158', '2.616', '2.418', '-4.273', '7.936', '4.551', '5.112', '3.310']
["Côte d'Ivoire", '9.272', '8.794', '8.843', '7.172', '7.412', '4.842', '6.721', '0.701', '7.062', '6.862', '6.200', '6.716']
['Croatia', '-0.399', '-0.423', '2.523', '3.563', '3.398', '2.822', '3.398', '-8.591', '13.788', '6.343', '2.831', '2.659']
['Cyprus', '-6.587', '-1.775', '3.417', '6.574', '5.734', '5.648', '5.537', '-3.443', '9.910', '5.059', '2.460', '2.958']
['Czech Republic', '-0.046', '2.262', '5.388', '2.537', '5.169', '3.220', '3.030', '-5.503', '3.553', '2.328', '-0.405', '1.958']
['Denmark', '0.935', '1.616', '2.343', '3.248', '2.819', '1.991', '1.493', '-2.423', '6.845', '2.731', '1.813', '2.128']
['Djibouti', '5.001', '7.193', '7.309', '7.123', '5.458', '4.774', '5.545', '1.316', '4.522', '3.876', '6.989', '5.373']
['Dominica', '-1.000', '4.754', '-2.732', '2.764', '-6.619', '3.548', '5.502', '-16.605', '6.892', '5.648', '4.726', '0.625']
['Dominican Republic', '4.875', '7.050', '6.927', '6.659', '4.667', '6.983', '5.052', '-6.720', '12.272', '4.858', '2.409', '5.003']
['Ecuador', '7.211', '4.226', '0.120', '-0.688', '5.970', '1.044', '0.165', '-9.245', '9.818', '6.186', '2.284', '2.463']
['Egypt', '3.302', '2.930', '4.360', '4.340', '4.191', '5.327', '5.548', '3.573', '3.253', '6.653', '3.760', '4.294']
['El Salvador', '2.235', '1.704', '2.400', '2.515', '2.262', '2.445', '2.432', '-7.901', '11.904', '2.799', '3.498', '2.390']
['Equatorial Guinea', '-4.133', '0.415', '-9.110', '-8.816', '-5.668', '-6.237', '-5.482', '-4.788', '-0.377', '3.246', '-5.947', '-4.363']
['Eritrea', '-10.456', '30.934', '-20.621', '7.391', '-10.015', '13.032', '3.836', 'n/a', 'n/a', 'n/a', 'n/a', '2.014']
['Estonia', '1.458', '3.011', '1.853', '3.155', '5.792', '3.784', '4.034', '-0.965', '7.249', '-0.461', '-3.006', '2.355']
['Eswatini', '3.861', '0.923', '2.227', '1.063', '2.027', '2.380', '2.692', '-1.560', '10.683', '0.476', '5.133', '2.719']
['Ethiopia', '9.900', '10.300', '10.400', '8.000', '10.210', '7.703', '9.037', '6.057', '6.265', '6.358', '7.176', '8.310']
['Fiji', '4.734', '5.604', '4.501', '2.446', '5.353', '3.812', '-0.581', '-17.040', '-4.881', '20.016', '8.045', '2.910']
['Finland', '-0.902', '-0.365', '0.544', '2.811', '3.192', '1.140', '1.224', '-2.355', '2.838', '1.335', '-0.957', '0.773']
['France', '0.576', '0.956', '1.113', '1.095', '2.291', '1.865', '1.843', '-7.540', '6.321', '2.526', '0.869', '1.083']
['Gabon', '5.517', '4.435', '3.879', '2.091', '0.473', '0.909', '3.823', '-1.815', '1.468', '3.037', '2.266', '2.371']
['The Gambia', '2.873', '-1.407', '4.058', '1.943', '4.823', '7.235', '6.222', '0.591', '5.256', '4.905', '5.555', '3.823']
['Georgia', '5.134', '4.091', '3.351', '3.450', '5.161', '6.062', '5.380', '-6.291', '10.644', '10.960', '7.474', '5.038']
['Germany', '0.432', '2.217', '1.487', '2.230', '2.680', '0.984', '1.071', '-3.829', '3.169', '1.804', '-0.305', '1.085']
['Ghana', '7.242', '2.856', '2.121', '3.373', '8.129', '6.200', '6.508', '0.514', '5.076', '3.078', '2.259', '4.305']
['Greece', '-2.516', '0.476', '-0.196', '-0.487', '1.092', '1.668', '1.880', '-9.316', '8.380', '5.557', '2.011', '0.777']
['Grenada', '2.351', '7.342', '6.445', '3.740', '4.439', '4.361', '0.677', '-13.757', '4.687', '7.321', '4.791', '2.945']
['Guatemala', '3.695', '4.444', '4.092', '2.678', '3.080', '3.407', '4.018', '-1.792', '8.002', '4.118', '3.474', '3.565']
['Guinea', '3.946', '3.697', '3.826', '10.821', '10.300', '6.358', '5.617', '4.709', '5.583', '3.972', '5.700', '5.866']
['Guinea-Bissau', '3.256', '0.965', '6.134', '5.307', '4.789', '3.761', '4.500', '1.500', '6.400', '4.200', '4.200', '4.092']
['Guyana', '3.653', '1.686', '0.687', '3.807', '3.734', '4.441', '5.353', '43.480', '20.060', '62.288', '32.963', '16.559']
['Haiti', '4.325', '1.723', '2.563', '1.812', '2.510', '1.668', '-1.685', '-3.343', '-1.798', '-1.682', '-1.864', '0.384']
['Honduras', '2.792', '3.058', '3.840', '3.893', '4.843', '3.845', '2.653', '-8.965', '12.534', '3.998', '3.500', '3.272']
['Hong Kong SAR', '3.102', '2.762', '2.388', '2.175', '3.796', '2.847', '-1.672', '-6.545', '6.454', '-3.681', '3.215', '1.349']
['Hungary', '1.803', '4.232', '3.707', '2.201', '4.272', '5.363', '4.864', '-4.563', '7.086', '4.555', '-0.908', '2.976']
['Iceland', '4.552', '1.687', '4.437', '6.304', '4.195', '4.889', '1.861', '-6.940', '5.149', '8.881', '4.064', '3.553']
['India', '6.386', '7.410', '7.996', '8.256', '6.795', '6.454', '3.871', '-5.778', '9.690', '6.987', '7.827', '5.990']
['Indonesia', '5.557', '5.007', '4.876', '5.033', '5.070', '5.174', '5.019', '-2.066', '3.703', '5.307', '5.048', '4.339']
['Iran', '-1.522', '4.985', '-1.425', '8.815', '2.759', '-1.838', '-3.071', '3.330', '4.720', '3.777', '4.709', '2.294']
['Iraq', '7.628', '0.738', '2.537', '15.199', '-3.399', '4.703', '5.368', '-12.055', '1.580', '6.983', '-2.176', '2.464']
['Ireland', '1.175', '8.829', '24.475', '1.766', '9.311', '8.471', '5.298', '6.617', '15.125', '9.433', '-3.199', '7.936']
['Israel', '4.231', '3.885', '2.314', '4.367', '4.273', '4.075', '3.785', '-1.465', '9.344', '6.470', '2.003', '3.935']
['Italy', '-1.841', '-0.005', '0.778', '1.293', '1.668', '0.926', '0.483', '-8.974', '8.310', '3.986', '0.921', '0.686']
['Jamaica', '0.224', '0.575', '0.869', '1.498', '0.679', '1.827', '0.970', '-9.920', '4.601', '5.222', '2.200', '0.795']
['Japan', '2.005', '0.296', '1.561', '0.754', '1.675', '0.643', '-0.402', '-4.147', '2.559', '0.957', '1.923', '0.711']
['Jordan', '2.610', '3.384', '2.497', '1.994', '2.474', '1.919', '1.751', '-1.103', '3.656', '2.428', '2.600', '2.201']
['Kazakhstan', '5.899', '4.300', '1.000', '0.900', '3.901', '4.100', '4.500', '-2.600', '4.100', '3.299', '5.101', '3.136']
['Kenya', '3.798', '5.020', '4.968', '4.214', '3.816', '5.671', '5.114', '-0.273', '7.590', '4.847', '5.507', '4.570']
['Kiribati', '7.731', '1.264', '11.265', '7.088', '3.749', '3.479', '3.264', '-0.562', '8.523', '3.905', '4.154', '4.896']
['Korea', '3.165', '3.202', '2.809', '2.947', '3.160', '2.907', '2.244', '-0.709', '4.305', '2.613', '1.357', '2.545']
['Kosovo', '5.340', '3.349', '5.916', '5.572', '4.825', '3.406', '4.757', '-5.341', '10.746', '4.278', '3.300', '4.195']
['Kuwait', '1.149', '0.501', '0.593', '2.926', '-4.712', '2.434', '1.328', '-5.274', '1.698', '6.138', '-2.231', '0.419']
['Kyrgyz Republic', '10.915', '4.024', '3.876', '4.336', '4.740', '3.459', '4.601', '-7.149', '5.507', '6.332', '4.196', '4.076']
['Lao P.D.R.', '8.026', '7.612', '7.270', '7.023', '6.851', '6.289', '4.652', '-0.435', '2.061', '2.252', '3.697', '5.027']
['Latvia', '2.008', '1.902', '3.885', '2.369', '3.312', '3.991', '0.588', '-3.514', '6.732', '2.955', '-0.306', '2.157']
['Lebanon', '3.828', '2.485', '0.461', '1.556', '0.903', '-1.885', '-6.915', '-25.907', '-10.000', 'n/a', 'n/a', '-3.942']
['Lesotho', '1.772', '2.068', '3.248', '1.887', '-2.734', '-1.510', '-3.058', '-5.303', '1.700', '1.600', '1.877', '0.140']
['Liberia', '8.836', '0.695', '0.007', '-1.630', '2.469', '1.242', '-2.516', '-2.967', '5.011', '4.811', '4.583', '1.867']
['Libya', '-17.998', '-23.043', '-0.843', '-1.493', '32.492', '7.941', '-11.196', '-29.456', '28.335', '-8.252', '10.156', '-1.214']
['Lithuania', '3.550', '3.537', '2.025', '2.519', '4.283', '3.993', '4.666', '-0.025', '6.285', '2.440', '-0.343', '2.994']
['Luxembourg', '3.172', '2.623', '2.269', '4.978', '1.317', '1.219', '2.916', '-0.910', '7.169', '1.380', '-1.095', '2.276']
['Macau SAR', '10.753', '-2.048', '-21.515', '-0.679', '9.860', '6.405', '-2.563', '-54.336', '23.535', '-21.402', '80.534', '2.595']
['Madagascar', '2.300', '3.339', '3.132', '3.993', '3.933', '3.194', '4.411', '-7.138', '5.740', '4.000', '3.800', '2.791']
['Malawi', '5.200', '5.700', '2.950', '2.270', '4.000', '4.392', '5.448', '0.913', '4.567', '0.800', '1.600', '3.440']
['Malaysia', '4.694', '6.007', '5.007', '4.450', '5.813', '4.843', '4.413', '-5.457', '3.298', '8.650', '3.680', '4.127']
['Maldives', '6.963', '7.801', '3.972', '6.572', '7.055', '8.668', '7.298', '-32.909', '37.687', '13.907', '4.424', '6.494']
['Mali', '2.295', '7.085', '6.172', '5.852', '5.305', '4.746', '4.765', '-1.244', '3.053', '3.475', '4.500', '4.182']
['Malta', '5.473', '7.634', '9.608', '3.381', '10.869', '7.416', '7.124', '-8.157', '12.514', '8.076', '5.614', '6.323']
['Marshall Islands', '3.610', '-1.158', '2.101', '2.144', '3.734', '5.659', '10.358', '-2.846', '1.112', '-0.676', '3.000', '2.458']
['Mauritania', '4.151', '4.275', '5.376', '1.261', '6.271', '4.773', '3.146', '-0.429', '0.737', '6.364', '4.811', '3.703']
['Mauritius', '3.360', '3.827', '3.691', '3.862', '3.938', '4.007', '2.891', '-14.547', '3.404', '8.881', '6.870', '2.744']
['Mexico', '0.852', '2.504', '2.702', '1.772', '1.872', '1.972', '-0.251', '-8.625', '5.739', '3.949', '3.229', '1.429']
['Micronesia', '-3.676', '-2.586', '4.434', '0.943', '2.255', '0.064', '3.820', '-1.870', '3.013', '-0.864', '0.766', '0.573']
['Moldova', '9.044', '5.000', '-0.338', '4.409', '4.200', '4.100', '3.600', '-8.300', '13.900', '-4.982', '1.032', '2.879']
['Mongolia', '11.649', '7.885', '2.410', '1.490', '5.637', '7.745', '5.602', '-4.558', '1.637', '5.033', '7.023', '4.687']
['Montenegro', '3.549', '1.784', '3.390', '2.949', '4.716', '5.078', '4.063', '-15.307', '13.043', '6.407', '6.000', '3.243']
['Morocco', '4.535', '2.669', '4.345', '0.521', '5.058', '3.066', '2.891', '-7.178', '8.021', '1.259', '3.017', '2.564']
['Mozambique', '6.571', '7.703', '7.393', '4.697', '2.638', '3.485', '2.318', '-1.220', '2.377', '4.360', '6.013', '4.212']
['Myanmar', '7.899', '8.200', '7.473', '6.408', '5.750', '6.405', '6.750', '-1.200', '-10.486', '-3.965', '2.546', '3.253']
['Namibia', '5.615', '6.093', '4.264', '0.034', '-1.027', '1.060', '-0.839', '-8.101', '3.525', '4.560', '3.154', '1.667']
['Nauru', '3.648', '16.423', '2.698', '4.363', '-6.011', '-1.219', '8.407', '1.982', '7.207', '2.841', '0.596', '3.729']
['Nepal', '3.525', '6.011', '3.976', '0.433', '8.977', '7.622', '6.657', '-2.370', '4.838', '5.613', '0.832', '4.192']
['Netherlands', '-0.127', '1.424', '1.958', '2.192', '2.911', '2.361', '1.955', '-3.885', '6.192', '4.326', '0.093', '1.764']
['New Zealand', '2.319', '3.766', '3.636', '3.945', '3.346', '3.497', '3.079', '-1.370', '5.628', '2.384', '0.633', '2.806']
['Nicaragua', '4.927', '4.785', '4.792', '4.563', '4.631', '-3.363', '-2.897', '-1.766', '10.347', '3.751', '4.686', '3.132']
['Niger', '5.311', '6.644', '4.393', '5.741', '5.001', '7.007', '6.143', '3.550', '1.399', '11.904', '1.409', '5.318']
['Nigeria', '5.394', '6.310', '2.653', '-1.617', '0.806', '1.923', '2.208', '-1.794', '3.647', '3.252', '2.860', '2.331']
['North Macedonia', '2.925', '3.629', '3.856', '2.848', '1.082', '2.881', '3.910', '-4.688', '4.511', '2.221', '1.027', '2.200']
['Norway', '1.016', '2.048', '1.857', '1.165', '2.464', '0.829', '1.124', '-1.278', '3.909', '3.006', '0.514', '1.514']
['Oman', '5.227', '1.292', '5.017', '5.046', '0.304', '1.287', '-1.130', '-3.378', '3.092', '4.311', '1.311', '2.034']
['Pakistan', '3.856', '3.556', '3.812', '4.072', '4.609', '6.096', '3.120', '-0.943', '5.770', '6.169', '-0.166', '3.632']
['Palau', '-1.612', '4.435', '9.549', '1.507', '-3.514', '1.261', '1.357', '-7.040', '-13.362', '-1.964', '0.800', '-0.780']
['Panama', '6.903', '5.067', '5.733', '4.953', '5.591', '3.685', '3.282', '-17.668', '15.836', '10.809', '7.317', '4.683']
['Papua New Guinea', '3.825', '13.544', '6.576', '5.492', '3.535', '-0.279', '4.480', '-3.167', '-0.780', '5.165', '2.681', '3.734']
['Paraguay', '8.293', '5.301', '2.957', '4.268', '4.810', '3.204', '-0.402', '-0.820', '4.017', '0.176', '4.477', '3.298']
['Peru', '5.852', '2.384', '3.252', '3.954', '2.522', '3.970', '2.240', '-10.869', '13.418', '2.684', '-0.552', '2.623']
['Philippines', '6.751', '6.348', '6.348', '7.149', '6.931', '6.341', '6.119', '-9.518', '5.715', '7.570', '5.568', '5.029']
['Poland', '0.857', '3.837', '4.383', '2.954', '5.140', '5.945', '4.450', '-2.020', '6.935', '5.260', '0.160', '3.446']
['Portugal', '-0.923', '0.792', '1.792', '2.019', '3.506', '2.849', '2.683', '-8.301', '5.737', '6.828', '2.280', '1.751']
['Puerto Rico', '-0.307', '-1.190', '-1.049', '-1.263', '-2.886', '-4.364', '1.679', '-4.186', '0.412', '3.207', '-0.700', '-0.968']
['Qatar', '5.556', '5.334', '4.753', '3.064', '-1.498', '1.235', '0.688', '-3.558', '1.627', '4.200', '1.558', '2.087']
['Romania', '0.270', '4.121', '3.160', '2.858', '8.197', '6.029', '3.853', '-3.677', '5.709', '4.595', '2.110', '3.384']
['Russia', '1.755', '0.736', '-1.973', '0.194', '1.827', '2.806', '2.198', '-2.654', '5.988', '-1.201', '3.585', '1.206']
['Rwanda', '4.730', '6.154', '8.867', '5.969', '3.931', '8.539', '9.472', '-3.380', '10.880', '8.158', '6.949', '6.388']
['Samoa', '0.107', '0.660', '3.850', '7.984', '1.406', '-0.610', '4.453', '-3.108', '-7.077', '-5.308', '7.990', '0.941']
['San Marino', '-0.820', '-0.649', '2.691', '2.338', '0.254', '1.484', '2.032', '-6.812', '14.228', '5.037', '2.304', '2.008']
['São Tomé and Príncipe', '5.120', '4.906', '1.540', '5.177', '4.113', '4.378', '2.014', '2.625', '1.899', '0.065', '-0.300', '2.867']
['Saudi Arabia', '2.535', '3.811', '4.509', '1.885', '0.911', '3.199', '1.098', '-3.582', '5.075', '7.486', '-0.755', '2.379']
['Senegal', '2.412', '6.224', '6.367', '6.356', '7.407', '6.209', '4.614', '1.342', '6.540', '4.000', '4.102', '5.052']

In [ ]:
df

,Country,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Avg.
0,Afghanistan,5.683,2.697,0.988,2.164,2.647,1.189,3.912,-2.351,-14.542,-6.240,n/a,-0.385
1,Albania,1.002,1.774,2.219,3.315,3.802,4.019,2.088,-3.302,8.909,4.884,3.297,2.906
2,Algeria,2.597,4.086,3.162,3.884,1.524,1.440,0.933,-5.017,3.805,3.616,4.184,2.201
3,Andorra,-3.548,2.504,1.434,3.710,0.346,1.589,2.016,-11.184,8.287,9.565,2.275,1.545
4,Angola,4.955,4.823,0.944,-2.580,-0.150,-1.316,-0.702,-5.638,1.199,3.045,0.470,0.459
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Samoa,0.107,0.660,3.850,7.984,1.406,-0.610,4.453,-3.108,-7.077,-5.308,7.990,0.941
146,San Marino,-0.820,-0.649,2.691,2.338,0.254,1.484,2.032,-6.812,14.228,5.037,2.304,2.008
147,São Tomé and Príncipe,5.120,4.906,1.540,5.177,4.113,4.378,2.014,2.625,1.899,0.065,-0.300,2.867
148,Saudi Arabia,2.535,3.811,4.509,1.885,0.911,3.199,1.098,-3.582,5.075,7.486,-0.755,2.379
149,Senegal,2.412,6.224,6.367,6.356,7.407,6.209,4.614,1.342,6.540,4.000,4.102,5.052

# Cleaning Data

In [ ]:
import numpy as np

df.replace(['n/a','na'], np.nan, inplace=True)

In [ ]:
df['2013'][0]

'5.683'

In [ ]:
type(df['2013'][0])

str

In [ ]:
for kolom in df.columns[1:]: # karna index negara tidak dijadikan float
  df[kolom] = pd.to_numeric(df[kolom], errors= 'coerce').astype('float64')

df

,Country,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Avg.
0,Afghanistan,5.683,2.697,0.988,2.164,2.647,1.189,3.912,-2.351,-14.542,-6.240,NaN,-0.385
1,Albania,1.002,1.774,2.219,3.315,3.802,4.019,2.088,-3.302,8.909,4.884,3.297,2.906
2,Algeria,2.597,4.086,3.162,3.884,1.524,1.440,0.933,-5.017,3.805,3.616,4.184,2.201
3,Andorra,-3.548,2.504,1.434,3.710,0.346,1.589,2.016,-11.184,8.287,9.565,2.275,1.545
4,Angola,4.955,4.823,0.944,-2.580,-0.150,-1.316,-0.702,-5.638,1.199,3.045,0.470,0.459
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Samoa,0.107,0.660,3.850,7.984,1.406,-0.610,4.453,-3.108,-7.077,-5.308,7.990,0.941
146,San Marino,-0.820,-0.649,2.691,2.338,0.254,1.484,2.032,-6.812,14.228,5.037,2.304,2.008
147,São Tomé and Príncipe,5.120,4.906,1.540,5.177,4.113,4.378,2.014,2.625,1.899,0.065,-0.300,2.867
148,Saudi Arabia,2.535,3.811,4.509,1.885,0.911,3.199,1.098,-3.582,5.075,7.486,-0.755,2.379
149,Senegal,2.412,6.224,6.367,6.356,7.407,6.209,4.614,1.342,6.540,4.000,4.102,5.052

In [ ]:
type(df['2013'][0])

numpy.float64

In [ ]:
for kolom in df.columns[1:]:
  df[kolom].fillna(0, inplace=True)
  # df[kolom].fillna(df[kolom].mean(), inplace=True)

df

<ipython-input-59-ab416b37c00b>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[kolom].fillna(0, inplace=True)

,Country,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Avg.
0,Afghanistan,5.683,2.697,0.988,2.164,2.647,1.189,3.912,-2.351,-14.542,-6.240,0.000,-0.385
1,Albania,1.002,1.774,2.219,3.315,3.802,4.019,2.088,-3.302,8.909,4.884,3.297,2.906
2,Algeria,2.597,4.086,3.162,3.884,1.524,1.440,0.933,-5.017,3.805,3.616,4.184,2.201
3,Andorra,-3.548,2.504,1.434,3.710,0.346,1.589,2.016,-11.184,8.287,9.565,2.275,1.545
4,Angola,4.955,4.823,0.944,-2.580,-0.150,-1.316,-0.702,-5.638,1.199,3.045,0.470,0.459
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Samoa,0.107,0.660,3.850,7.984,1.406,-0.610,4.453,-3.108,-7.077,-5.308,7.990,0.941
146,San Marino,-0.820,-0.649,2.691,2.338,0.254,1.484,2.032,-6.812,14.228,5.037,2.304,2.008
147,São Tomé and Príncipe,5.120,4.906,1.540,5.177,4.113,4.378,2.014,2.625,1.899,0.065,-0.300,2.867
148,Saudi Arabia,2.535,3.811,4.509,1.885,0.911,3.199,1.098,-3.582,5.075,7.486,-0.755,2.379
149,Senegal,2.412,6.224,6.367,6.356,7.407,6.209,4.614,1.342,6.540,4.000,4.102,5.052

# train test split

In [ ]:
from sklearn.model_selection import train_test_split

kolom_x = ['2020','2021','2022']

x = np.array(df[kolom_x])
y = np.array(df['2023'])

x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=0
)

# Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error #semakin kecil (mendekati 0) MSE, semakin bagus


linear_model = LinearRegression()
#training
linear_model.fit(x_train,y_train)

#testing
y_pred = linear_model.predict(x_test)
mse = mean_squared_error(y_pred,y_test) #hasil prediksi dan data asli
print(f"hasil MSE = {mse}")

hasil MSE = 272.9292859962986

# Ridge Regression

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error #semakin kecil (mendekati 0) MSE, semakin bagus


ridge_model = Ridge() #lambda = alpha untuk mengukur seberapa besar penaltinya
#training
ridge_model.fit(x_train,y_train)

#testing
y_pred = ridge_model.predict(x_test)
mse = mean_squared_error(y_pred,y_test) #hasil prediksi dan data asli
print(f"hasil MSE = {mse}")

hasil MSE = 272.8268546995363

# Lasso Regression

In [ ]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error #semakin kecil (mendekati 0) MSE, semakin bagus


lasso_model = Lasso() #lambda = alpha untuk mengukur seberapa besar penaltinya
#training
lasso_model.fit(x_train,y_train)

#testing
y_pred = lasso_model.predict(x_test)
mse = mean_squared_error(y_pred,y_test) #hasil prediksi dan data asli
print(f"hasil MSE = {mse}")

hasil MSE = 254.65191071158338

# PolyRegresi

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

PolyRegresi = make_pipeline(PolynomialFeatures(degree=5),LinearRegression())
PolyRegresi.fit(x_train,y_train)

#testing
y_pred = PolyRegresi.predict(x_test)
mse = mean_squared_error(y_pred,y_test) #hasil prediksi dan data asli
print(f"hasil MSE = {mse}")

hasil MSE = 73625713071.56418

#<a href="https://www.linkedin.com/in/m-riziq-sa"><img src="https://img.shields.io/badge/-© 2024 M. Riziq Sirfatullah Alfarizi-417DAC?style=for-the-badge&logoColor=white"/></a>