<h1>M Riziq Sirfatullah Alfarizi

<h1>i.2211266

# Ensemble Learning for regresion

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("fatemehmehrparvar/obesity-levels")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/fatemehmehrparvar/obesity-levels?dataset_version_number=1...

100%|██████████| 57.6k/57.6k [00:00<00:00, 31.3MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/fatemehmehrparvar/obesity-levels/versions/1

In [2]:
import os
dataset_path = '/root/.cache/kagglehub/datasets/fatemehmehrparvar/obesity-levels/versions/1'
files = os.listdir(dataset_path)
print('Nama files: ', files)

Nama files:  ['ObesityDataSet_raw_and_data_sinthetic.csv']

In [3]:
import pandas as pd
data_file = os.path.join(dataset_path, 'ObesityDataSet_raw_and_data_sinthetic.csv')
data = pd.read_csv(data_file)
data

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.000000,Female,1.620000,64.000000,no,no,2.0,3.0,no,no,2.000000,yes,0.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
1,21.000000,Female,1.520000,56.000000,Sometimes,no,3.0,3.0,yes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,23.000000,Male,1.800000,77.000000,Frequently,no,2.0,3.0,no,no,2.000000,yes,2.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight
3,27.000000,Male,1.800000,87.000000,Frequently,no,3.0,3.0,no,no,2.000000,no,2.000000,0.000000,Sometimes,Walking,Overweight_Level_I
4,22.000000,Male,1.780000,89.800000,Sometimes,no,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             2111 non-null   float64
 1   Gender                          2111 non-null   object
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   CALC                            2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   SCC                             2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  family_history_with_overweight  2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CAEC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [5]:
data['NObeyesdad'].unique()

array(['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II',
       'Obesity_Type_I', 'Insufficient_Weight', 'Obesity_Type_II',
       'Obesity_Type_III'], dtype=object)

In [6]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
data['NObeyesdad_encoded'] = label_encoder.fit_transform(data['NObeyesdad'])
data

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,NObeyesdad_encoded
0,21.000000,Female,1.620000,64.000000,no,no,2.0,3.0,no,no,2.000000,yes,0.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight,1
1,21.000000,Female,1.520000,56.000000,Sometimes,no,3.0,3.0,yes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight,1
2,23.000000,Male,1.800000,77.000000,Frequently,no,2.0,3.0,no,no,2.000000,yes,2.000000,1.000000,Sometimes,Public_Transportation,Normal_Weight,1
3,27.000000,Male,1.800000,87.000000,Frequently,no,3.0,3.0,no,no,2.000000,no,2.000000,0.000000,Sometimes,Walking,Overweight_Level_I,5
4,22.000000,Male,1.780000,89.800000,Sometimes,no,2.0,1.0,no,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,4
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,4
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,4
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,4
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,4

In [7]:
data.columns

Index(['Age', 'Gender', 'Height', 'Weight', 'CALC', 'FAVC', 'FCVC', 'NCP',
       'SCC', 'SMOKE', 'CH2O', 'family_history_with_overweight', 'FAF', 'TUE',
       'CAEC', 'MTRANS', 'NObeyesdad', 'NObeyesdad_encoded'],
      dtype='object')

In [8]:
x = data.drop(columns = ['Gender','CALC', 'FAVC', 'SCC', 'SMOKE','family_history_with_overweight',
                          'CAEC', 'MTRANS', 'NObeyesdad',])# data input
y = data['Age'] # target

## Begging (bootstrap aggregating)

Bagging merupakan teknik ensemble yang menggunakan beberapa model dasar, kemudian dilatih secara independen pada subset data ynga diambil sampling (sampling dengan penggantian). Prediksi akhir dilakukan dengan cara menggabungkan hasil semua model, biasanya dengan voting (untuk klasifikasi) atau rata-rata (untuk regresi)

In [10]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.35, random_state = 0)

#Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators = 100, random_state = 0)
rf_model.fit(x_train, y_train)

#predik
y_pred = rf_model.predict(x_test)

# untuk cek Overfitting atau underfitting
y_pred_train = rf_model.predict(x_train)

#evaluasi
print(f'train MSE = {mean_squared_error(y_pred_train,y_train)}')
print(f'MSE = {mean_squared_error(y_pred,y_test)}')
print(f'train MAE = {mean_absolute_error(y_pred_train,y_train)}')
print(f'MAE = {mean_absolute_error(y_pred,y_test)}')

train MSE = 0.003717283094338356
MSE = 0.0898786169039596
train MAE = 0.010680423347910296
MAE = 0.03659092840324742

## Boosting

Boosting merupakan teknik ensemble yang menggabungkan model dasar secara berurutan. setiap model baru mencoba untuk memperbaiki kesalahan dari model sebelumnya dengan memberikan bobot lebih besar pada data yang sulit di prediksi

###Adaboost

Membangun Model secara bertahap, dimana model berikut berfokus pada kesalahan model sebelumnya

In [12]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.35, random_state = 0)

#Base Model
base_model = DecisionTreeRegressor(max_depth = 10)

#AdaBoost Regressor
adaboost_model = AdaBoostRegressor(estimator = base_model, n_estimators=100, random_state=0)
adaboost_model.fit(x_train,y_train)

#Prediksi
y_pred = adaboost_model.predict(x_test)
y_pred_train = adaboost_model.predict(x_train)

# Evaluasi
print(f'MSE = {mean_squared_error(y_pred,y_test)}')
print(f'MSE = {mean_squared_error(y_pred_train,y_train)}')
print(f'MAE = {mean_absolute_error(y_pred,y_test)}')
print(f'MAE = {mean_absolute_error(y_pred_train,y_train)}')

MSE = 0.053081481781887645
MSE = 9.699623780749733e-06
MAE = 0.029911779394438315
MAE = 0.0011923076692068673

### Gradient Boosting:

merupakan teknik ensemble dengan meminimalkan loss function dengan cara menyesuaikan model baru terhadap kesalahan

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.35, random_state = 0)

# Gradient Boosting Regressor
gb_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=7,random_state=0)
gb_model.fit(x_train, y_train)

# predik
y_pred = gb_model.predict(x_test)

# evaluasi
print(f'MSE = {mean_squared_error(y_pred,y_test)}')
print(f'MAE = {mean_absolute_error(y_pred,y_test)}')

### XGBoost:

Merupakan implementasi yang lebih cepat dan dioptimalkan dari Gradient Boosting, Kelebihannya adalah mendukung paralelisasi, regularisasi, dan dapat mengendalikan overfitting

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state = 0)

# XGB Regressor
xgb_model = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=10,random_state=0)
xgb_model.fit(x_train, y_train)

# predik
y_pred = xgb_model.predict(x_test)

# evaluasi
print(f'MSE = {mean_squared_error(y_pred,y_test)}')
print(f'MAE = {mean_absolute_error(y_pred,y_test)}')

## Stacking

Staking adalah teknik ensemble yang menggabungkan prediksi dari beberapa model dasar dengan menggabungkan meta-model(model tingkat kedua) untuk membuat prediksi akhir.

In [ ]:
from sklearn.ensemble import StackingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.34, random_state = 0)

#Base Model
base_model = [
    ('rf',RandomForestRegressor(n_estimators=100, random_state=0)),
    ('svr', SVR(kernel='linear'))
]
#Meta Learner
meta_learner = LinearRegression()

#Stacking Re
stacking_model = StackingRegressor(estimators = base_model, final_estimator = meta_learner)
stacking_model.fit(x_train,y_train)

#Prediksi
y_pred = stacking_model.predict(x_test)
# evaluasi
print(f'MSE = {mean_squared_error(y_pred,y_test)}')
print(f'MAE = {mean_absolute_error(y_pred,y_test)}')

# Tugas

Buatlah Implementasi ketiga metode Ensemble Learning dengan menggunakan model/parameter yang berbeda dibandingkan dengan model/parameter yang digunakan pada pertemuan ini!